# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.pl.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 26 of 135 keys, and 8 orphan(s) the base file no longer has.

flightdata-pointCameraHereToolStripMenuItem-Text = Skieruj kamerę tutaj
flightdata-BUT_quickmanual-Text = &Manualny
flightdata-BUT_playlog-Text = Odtwarzanie/Pauza
flightdata-goHereToolStripMenuItem-Text = Leć tutaj
flightdata-BUT_RAWSensor-Text = Widok surowych danych czujników
# orphan: no entry `TXT_alt.Text` in GCSViews/FlightData.resx
flightdata-TXT_alt-Text = 0
# orphan: no entry `lbl_windvel.Text` in GCSViews/FlightData.resx
flightdata-lbl_windvel-Text = Pr: 0
# orphan: no entry `TXT_long.Text` in GCSViews/FlightData.resx
flightdata-TXT_long-Text = 0
flightdata-BUT_log2kml-Text = Log > KML
flightdata-label1-Text = Zoom
flightdata-BUT_clear_track-Text = Wyczyść trasę
# orphan: no entry `dataGridViewImageColumn1.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn1-HeaderText = Góra
# orphan: no entry `BUT_script.Text` in GCSViews/FlightData.resx
flightdata-BUT_script-Text = Skrypt
flightdata-tabGauges-Text = Wskaźniki
flightdata-CHK_autopan-Text = Auto przes.
flightdata-BUT_joystick-Text = Joystick
flightdata-CB_tuning-Text = Strojenie
# orphan: no entry `dataGridViewImageColumn2.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn2-HeaderText = Dół
flightdata-BUTactiondo-Text = Wykonaj akcję
flightdata-BUTrestartmission-Text = Restart misji
# orphan: no entry `TXT_lat.Text` in GCSViews/FlightData.resx
flightdata-TXT_lat-Text = 0
flightdata-tabActions-Text = Akcje
flightdata-BUT_Homealt-Text = Ustaw wysokość startu
# orphan: no entry `lbl_winddir.Text` in GCSViews/FlightData.resx
flightdata-lbl_winddir-Text = Kierunek: 0
flightdata-BUT_loadtelem-Text = Załaduj Log
flightdata-recordHudToAVIToolStripMenuItem-Text = Zapisz HUD w pliku AVI
flightdata-tabStatus-Text = Status
flightdata-BUT_quickauto-Text = &Auto
flightdata-BUT_setwp-Text = Ustaw WP
flightdata-tabTLogs-Text = Logi telemetrii
flightdata-lbl_logpercent-Text = 0.00 %
flightdata-BUT_setmode-Text = Ustaw tryb
flightdata-stopRecordToolStripMenuItem-Text = Zatrzymaj rejestrację
flightdata-BUT_quickrtl-Text = &RTL
