# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.zh-TW.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 21 of 135 keys, and 3 orphan(s) the base file no longer has.

flightdata-goHereToolStripMenuItem-Text = 飛到這里
flightdata-BUT_joystick-Text = 飛行摇桿
flightdata-BUT_quickmanual-Text = 手動
flightdata-BUT_quickrtl-Text = 返航
flightdata-BUT_quickauto-Text = 自動
flightdata-BUT_setwp-Text = 設置航點
flightdata-BUT_setmode-Text = 設置模式
flightdata-BUT_clear_track-Text = 清除路徑
flightdata-BUT_Homealt-Text = 設置起始高度
flightdata-BUT_RAWSensor-Text = 感應器原始數據
flightdata-BUTrestartmission-Text = 重啟任務
flightdata-BUTactiondo-Text = 執　　行
flightdata-tabActions-Text = 動作
flightdata-tabGauges-Text = 儀表
flightdata-BUT_playlog-Text = 播放/暂停
flightdata-BUT_loadtelem-Text = 加載記錄
flightdata-label1-Text = 縮放
flightdata-CHK_autopan-Text = 自動平移地圖
flightdata-CB_tuning-Text = 舵機調整
# orphan: no entry `BUT_script.Text` in GCSViews/FlightData.resx
flightdata-BUT_script-Text = 脚本
# orphan: no entry `lbl_winddir.Text` in GCSViews/FlightData.resx
flightdata-lbl_winddir-Text = 風向: 0
# orphan: no entry `lbl_windvel.Text` in GCSViews/FlightData.resx
flightdata-lbl_windvel-Text = 風速: 0
flightdata-recordHudToAVIToolStripMenuItem-Text = 錄製為AVI
flightdata-stopRecordToolStripMenuItem-Text = 停止錄製
