# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.it-IT.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 38 of 135 keys, and 8 orphan(s) the base file no longer has.

flightdata-pointCameraHereToolStripMenuItem-Text = Punta qui la Telecamera
flightdata-BUT_quickmanual-Text = &Manuale
flightdata-tabServo-Text = Servo
flightdata-BUT_playlog-Text = Avvia/Pausa
flightdata-goHereToolStripMenuItem-Text = Vola qui
flightdata-BUT_RAWSensor-Text = Vista RAW del Sensore
# orphan: no entry `TXT_alt.Text` in GCSViews/FlightData.resx
flightdata-TXT_alt-Text = 0
# orphan: no entry `lbl_windvel.Text` in GCSViews/FlightData.resx
flightdata-lbl_windvel-Text = Vel: 0
# orphan: no entry `TXT_long.Text` in GCSViews/FlightData.resx
flightdata-TXT_long-Text = 0
flightdata-lbl_hdop-Text = hdop: 0
flightdata-BUT_log2kml-Text = Log -> KML
flightdata-label1-Text = Zoom
flightdata-BUT_clear_track-Text = Pulisci Traccia
flightdata-BUT_ARM-Text = Arma / Disarma
# orphan: no entry `dataGridViewImageColumn1.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn1-HeaderText = Su
flightdata-userItemsToolStripMenuItem-Text = Elementi Utente
# orphan: no entry `BUT_script.Text` in GCSViews/FlightData.resx
flightdata-BUT_script-Text = Script
flightdata-tabGauges-Text = Strumenti
flightdata-CHK_autopan-Text = Auto Panoramica
flightdata-setMJPEGSourceToolStripMenuItem-Text = Setta sorgente MJPEG{" "}
flightdata-BUT_joystick-Text = Joystick
flightdata-CB_tuning-Text = Tuning
flightdata-triggerCameraToolStripMenuItem-Text = Trigger Camera ORA
# orphan: no entry `dataGridViewImageColumn2.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn2-HeaderText = Giù
flightdata-lbl_sats-Text = Sats: 0
flightdata-BUTactiondo-Text = Fai un Azione
flightdata-BUTrestartmission-Text = Riavvia Missione
flightdata-setAspectRatioToolStripMenuItem-Text = Imposta "Aspect Ratio"
# orphan: no entry `TXT_lat.Text` in GCSViews/FlightData.resx
flightdata-TXT_lat-Text = 0
flightdata-tabActions-Text = Azioni
flightdata-BUT_Homealt-Text = Imposta la quota della "Home"
flightdata-tabQuick-Text = Quick
# orphan: no entry `lbl_winddir.Text` in GCSViews/FlightData.resx
flightdata-lbl_winddir-Text = Dir: 0
flightdata-BUT_loadtelem-Text = Carica Log
flightdata-recordHudToAVIToolStripMenuItem-Text = Registra Hud in AVI
flightdata-tabStatus-Text = Stato
flightdata-BUT_quickauto-Text = &Auto
flightdata-BUT_setwp-Text = Imposta WP
flightdata-tabTLogs-Text = Logs Telemetria
flightdata-lbl_logpercent-Text = 0.00 %
flightdata-flightPlannerToolStripMenuItem-Text = Flight Planner
flightdata-BUT_setmode-Text = Inposta Modo
flightdata-lbl_playbackspeed-Text = x 1.0
flightdata-stopRecordToolStripMenuItem-Text = Ferma Registrazione
flightdata-BUT_quickrtl-Text = &RTL
flightdata-flyToHereAltToolStripMenuItem-Text = Vola QUI Alt
