// Copyright (C) 2026 David "Buzz" Bussenschutt
//
// This file is part of MissionPlannerRust, a Rust implementation derived from
// Mission Planner (Copyright (C) 2010-2024 Michael Oborne and contributors,
// https://github.com/ArduPilot/MissionPlanner); NOTICE records the changes.
//
// MissionPlannerRust is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by the
// Free Software Foundation, version 3 of the License.
//
// MissionPlannerRust is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU General Public License along with
// MissionPlannerRust. If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-only

//! `cargo xtask ledger`, driven as a person or CI would drive it: through the binary, over a
//! small C# tree each test writes for itself.
//!
//! The fixture holds one file for every rule the classifier has and for each way a rule could
//! over-match (a file named like a vendored one, a form whose name ends in `Settings.Designer.cs`),
//! so a wrong precedence or a prefix without its slash fails here rather than silently moving a
//! few hundred rows of the real ledger into the wrong tier.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use sha2::{Digest, Sha256};

/// The resgen stamp: what makes a designer file generated rather than a form.
const STAMPED: &str = "//------\n// <auto-generated>\n//     This code was generated by a tool.\n\
                       // </auto-generated>\n//------\nnamespace Gen {\n}\n";

/// A form's designer half: no stamp.
const FORM: &str = "namespace MissionPlanner {\n    partial class Form {\n        \
                    private void InitializeComponent() { }\n    }\n}\n";

/// Every file in the fixture tree and the tier it must land in.
const EXPECTED: &[(&str, &str)] = &[
    // T3 by default, and the traps next to each rule.
    ("GCSViews/FlightData.cs", "T3"),
    ("ExtLibs/Utilities/MatrixHelper.cs", "T3"),
    ("ExtLibs/GMap.NET.CoreExtras/Extra.cs", "T3"),
    ("ExtLibs/Mavlink/MavlinkParse.cs", "T3"),
    ("ExtLibs/DroneCAN/DroneCAN.cs", "T3"),
    ("ExtLibs/WebAPIs/Dowding/Dowding.cs", "T3"),
    ("Plugins/example.cs", "T3"),
    ("Sizes/s199.cs", "T3"),
    ("Sizes/m200.cs", "T3"),
    ("Sizes/m599.cs", "T3"),
    ("Sizes/l600.cs", "T3"),
    ("Sizes/l1500.cs", "T3"),
    ("Sizes/xl1501.cs", "T3"),
    ("Namespaces/filescoped.cs", "T3"),
    ("Namespaces/bom.cs", "T3"),
    ("Namespaces/commented.cs", "T3"),
    ("Namespaces/unterminated.cs", "T3"),
    // T0: a vendored directory, an exact vendored file, and what goes down with a library.
    ("ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.cs", "T0"),
    (
        "ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.Designer.cs",
        "T0",
    ),
    ("ExtLibs/ZedGraph/Properties/Resources.Designer.cs", "T0"),
    ("ExtLibs/Utilities/Matrix.cs", "T0"),
    (
        "ExtLibs/Mavlink/pymavlink/generator/CS/MavlinkParse.cs",
        "T0",
    ),
    // T1: named generator output, and designer files by their stamp.
    ("ExtLibs/Mavlink/Mavlink.cs", "T1"),
    (
        "ExtLibs/DroneCAN/out/src/uavcan.protocol.NodeStatus.cs",
        "T1",
    ),
    (
        "ExtLibs/DroneCAN/out/include/uavcan.protocol.NodeStatus.cs",
        "T1",
    ),
    ("ExtLibs/DroneCAN/canard_dsdlc/messages.cs", "T1"),
    ("ExtLibs/WebAPIs/Dowding/src/Dowding/Api/ZoneApi.cs", "T1"),
    ("Properties/Resources.Designer.cs", "T1"),
    ("ExtLibs/Controls/HUDT.Designer.cs", "T1"),
    (
        "ExtLibs/Xamarin/Xamarin.Android/Resources/Resource.designer.cs",
        "T1",
    ),
    // T2: forms, whatever their name says.
    ("GCSViews/FlightData.Designer.cs", "T2"),
    ("Controls/DefaultSettings.Designer.cs", "T2"),
    ("Log/lower.designer.cs", "T2"),
    // T4: non-desktop heads, including their unstamped designer files.
    ("ExtLibs/Xamarin/Xamarin/MainPage.xaml.cs", "T4"),
    ("ExtLibs/Xamarin/Xamarin/Page.Designer.cs", "T4"),
    ("ExtLibs/uno/UnoUI/UnoUI.Droid/MainActivity.cs", "T4"),
];

struct Fixture {
    root: PathBuf,
}

impl Fixture {
    /// A fresh tree, an empty Rust repo beside it, and no ledger yet.
    fn new(name: &str) -> Fixture {
        let root = Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join("ledger")
            .join(name);
        let _ = fs::remove_dir_all(&root);
        let fixture = Fixture { root };
        for (path, _) in EXPECTED {
            let content = if path.to_ascii_lowercase().ends_with(".designer.cs") {
                if path.contains("Resource") || path.contains("HUDT") {
                    STAMPED.to_owned()
                } else {
                    FORM.to_owned()
                }
            } else {
                format!("namespace Fixture.{} {{\n}}\n", stem(path))
            };
            fixture.put(path, &content);
        }
        for (path, lines) in [
            ("Sizes/s199.cs", 199),
            ("Sizes/m200.cs", 200),
            ("Sizes/m599.cs", 599),
            ("Sizes/l600.cs", 600),
            ("Sizes/l1500.cs", 1500),
            ("Sizes/xl1501.cs", 1501),
        ] {
            fixture.put(path, &"//\n".repeat(lines));
        }
        fixture.put(
            "Namespaces/filescoped.cs",
            "using System;\nnamespace Foo.Bar;\n",
        );
        fixture.put("Namespaces/bom.cs", "\u{feff}namespace Bom.First\n{\n}\n");
        fixture.put(
            "Namespaces/commented.cs",
            "/*\nnamespace Not.This\n*/\n// namespace Nor.This\nnamespace Real.One{}\n",
        );
        fixture.put("Namespaces/unterminated.cs", "namespace NoNewline {}");
        fixture.put("Plugins/example.cs", "using System;\nclass Example {}\n");
        // Two project files in one directory: the first by name wins.
        fixture.put("MissionPlannerLib.csproj", "<Project/>");
        fixture.put("MissionPlanner.csproj", "<Project/>");
        fixture.put("ExtLibs/ZedGraph/ZedGraph.csproj", "<Project/>");
        // Not C# sources, whatever they look like.
        fixture.put(".git/objects/ignored.cs", "namespace Git {}\n");
        fixture.put("Upper.CS", "namespace Upper {}\n");
        fixture.put("notes.cs.txt", "namespace Text {}\n");
        fs::create_dir_all(fixture.repo().join("ledger")).unwrap();
        fixture
    }

    fn tree(&self) -> PathBuf {
        self.root.join("tree")
    }

    fn repo(&self) -> PathBuf {
        self.root.join("repo")
    }

    fn ledger(&self) -> PathBuf {
        self.repo().join("ledger/ledger.csv")
    }

    fn put(&self, path: &str, content: &str) {
        put(&self.tree().join(path), content);
    }

    /// Runs `xtask ledger <command>` against this fixture.
    fn run(&self, command: &str) -> Output {
        self.run_with(command, &self.tree())
    }

    fn run_with(&self, command: &str, tree: &Path) -> Output {
        Command::new(env!("CARGO_BIN_EXE_xtask"))
            .args(["ledger", command, "--tree"])
            .arg(tree)
            .arg("--ledger")
            .arg(self.ledger())
            .arg("--repo")
            .arg(self.repo())
            .output()
            .unwrap()
    }

    fn init(&self) -> Output {
        let out = self.run("init");
        assert!(out.status.success(), "init failed: {}", text(&out));
        out
    }

    fn csv(&self) -> String {
        fs::read_to_string(self.ledger()).unwrap()
    }

    /// The row for `path`, by column name. Only rows as `init` wrote them (no quoting) are read
    /// this way; that is the point: the test's reader does not share the tool's.
    fn row(&self, path: &str) -> Vec<(String, String)> {
        let csv = self.csv();
        let mut lines = csv.lines();
        let header: Vec<String> = lines
            .next()
            .unwrap()
            .split(',')
            .map(str::to_owned)
            .collect();
        let line = lines
            .find(|l| l.split(',').next() == Some(path))
            .unwrap_or_else(|| panic!("no row for {path}"));
        header
            .into_iter()
            .zip(line.split(',').map(str::to_owned))
            .collect()
    }

    fn get(&self, path: &str, column: &str) -> String {
        self.row(path)
            .into_iter()
            .find(|(c, _)| c == column)
            .unwrap_or_else(|| panic!("no column {column}"))
            .1
    }

    /// Rewrites columns of one row, quoting as RFC 4180 requires.
    fn edit(&self, path: &str, changes: &[(&str, &str)]) {
        let row = self.row(path);
        let old: Vec<String> = row.iter().map(|(_, v)| quote(v)).collect();
        let new: Vec<String> = row
            .iter()
            .map(|(column, value)| {
                let changed = changes.iter().find(|(c, _)| c == column);
                quote(changed.map_or(value.as_str(), |(_, v)| v))
            })
            .collect();
        let csv = self.csv().replace(
            &format!("{}\n", old.join(",")),
            &format!("{}\n", new.join(",")),
        );
        fs::write(self.ledger(), csv).unwrap();
    }

    /// `check`, which must fail, naming every one of `offenders`.
    fn check_fails(&self, offenders: &[&str]) -> String {
        let out = self.run("check");
        let text = text(&out);
        assert_eq!(out.status.code(), Some(1), "check should fail:\n{text}");
        for offender in offenders {
            assert!(
                text.contains(offender),
                "check did not name `{offender}`:\n{text}"
            );
        }
        text
    }

    fn check_passes(&self) -> String {
        let out = self.run("check");
        let text = text(&out);
        assert!(out.status.success(), "check should pass:\n{text}");
        text
    }
}

fn put(path: &Path, content: &str) {
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

fn stem(path: &str) -> String {
    path.rsplit('/')
        .next()
        .unwrap()
        .split('.')
        .next()
        .unwrap()
        .replace('-', "_")
}

fn quote(field: &str) -> String {
    if field.contains([',', '"', '\n']) {
        format!("\"{}\"", field.replace('"', "\"\""))
    } else {
        field.to_owned()
    }
}

fn text(out: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    )
}

#[test]
fn classifier_puts_each_file_in_its_tier() {
    let f = Fixture::new("classifier");
    f.init();
    let rows = f.csv().lines().count() - 1;
    assert_eq!(
        rows,
        EXPECTED.len(),
        "one row per .cs file and nothing else"
    );
    let disposition = |tier: &str| match tier {
        "T0" => "delete",
        "T1" => "regenerate",
        "T2" => "extract",
        "T3" => "hand-port",
        _ => "drop-pending-owner",
    };
    let mut wrong = Vec::new();
    for (path, tier) in EXPECTED {
        let got = f.get(path, "tier");
        if got != *tier {
            wrong.push(format!("{path}: {got}, expected {tier}"));
        }
        assert_eq!(f.get(path, "disposition"), disposition(tier), "{path}");
        assert_eq!(f.get(path, "state"), "ready", "{path}");
    }
    assert!(wrong.is_empty(), "misclassified:\n{}", wrong.join("\n"));
}

#[test]
fn init_measures_every_column_it_owns_and_leaves_the_rest_empty() {
    let f = Fixture::new("measure");
    f.init();

    let bytes = fs::read(f.tree().join("GCSViews/FlightData.cs")).unwrap();
    assert_eq!(
        f.get("GCSViews/FlightData.cs", "sha256"),
        format!("{:x}", Sha256::digest(&bytes))
    );
    assert_eq!(f.get("GCSViews/FlightData.cs", "loc"), "2");

    // The root holds two project files; the first by name is the application.
    assert_eq!(
        f.get("GCSViews/FlightData.cs", "csproj"),
        "MissionPlanner.csproj"
    );
    assert_eq!(
        f.get("ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.cs", "csproj"),
        "ExtLibs/ZedGraph/ZedGraph.csproj"
    );

    for (path, namespace) in [
        ("GCSViews/FlightData.cs", "Fixture.FlightData"),
        ("Namespaces/filescoped.cs", "Foo.Bar"),
        ("Namespaces/bom.cs", "Bom.First"),
        ("Namespaces/commented.cs", "Real.One"),
        ("Namespaces/unterminated.cs", "NoNewline"),
        ("Plugins/example.cs", ""),
    ] {
        assert_eq!(f.get(path, "namespace"), namespace, "{path}");
    }
    // `wc -l`: a last line without a newline is not counted, as in PLAN.md's totals.
    assert_eq!(f.get("Namespaces/unterminated.cs", "loc"), "0");

    for (path, size) in [
        ("Sizes/s199.cs", "S"),
        ("Sizes/m200.cs", "M"),
        ("Sizes/m599.cs", "M"),
        ("Sizes/l600.cs", "L"),
        ("Sizes/l1500.cs", "L"),
        ("Sizes/xl1501.cs", "XL"),
    ] {
        assert_eq!(f.get(path, "size"), size, "{path}");
    }

    for (column, value) in f.row("GCSViews/FlightData.cs") {
        let measured = [
            "path",
            "loc",
            "namespace",
            "csproj",
            "tier",
            "disposition",
            "size",
            "state",
            "sha256",
        ];
        if !measured.contains(&column.as_str()) {
            assert!(
                value.is_empty(),
                "{column} should start empty, is `{value}`"
            );
        }
    }
}

#[test]
fn two_inits_are_byte_identical_and_a_second_run_changes_nothing() {
    let a = Fixture::new("determinism-a");
    let b = Fixture::new("determinism-b");
    a.init();
    b.init();
    let first = a.csv();
    assert_eq!(
        first,
        b.csv(),
        "two trees with the same files, two different ledgers"
    );
    a.init();
    assert_eq!(
        first,
        a.csv(),
        "a refresh over an unchanged tree rewrote the ledger"
    );
    let lines: Vec<&str> = first.lines().skip(1).collect();
    let mut sorted = lines.clone();
    sorted.sort_by_key(|l| l.split(',').next().unwrap().to_owned());
    assert_eq!(lines, sorted, "rows are not in path order");
    assert!(first.ends_with('\n') && !first.contains('\r'));
}

#[test]
fn a_spreadsheet_save_is_read_and_a_refresh_normalises_it() {
    let f = Fixture::new("spreadsheet");
    f.init();
    let original = f.csv();
    // What a spreadsheet on Windows writes back: a byte order mark and CRLF.
    fs::write(
        f.ledger(),
        format!("\u{feff}{}", original.replace('\n', "\r\n")),
    )
    .unwrap();
    f.check_passes();
    f.init();
    assert_eq!(f.csv(), original);
}

#[test]
fn refresh_keeps_hand_columns_and_flags_upstream_changes() {
    let f = Fixture::new("refresh");
    f.init();
    let notes = "owner said: keep \"as is\", for now\nsecond line";
    f.edit(
        "GCSViews/FlightData.cs",
        &[
            ("state", "ported"),
            ("target_crate", "mp-gui"),
            ("unit_id", "fly-1"),
            ("owner", "agent-7"),
            ("attempts", "2"),
            ("omissions", "none; the HUD"),
            ("notes", notes),
        ],
    );
    f.edit(
        "ExtLibs/Mavlink/MavlinkParse.cs",
        &[("disposition", "regenerate"), ("owner", "buzz")],
    );
    f.edit("ExtLibs/DroneCAN/DroneCAN.cs", &[("state", "ported")]);
    f.edit(
        "GCSViews/FlightData.Designer.cs",
        &[("disposition", "hand-port")],
    );

    // Upstream edits two files: one under work, one nobody has touched. A third appears.
    f.put(
        "GCSViews/FlightData.cs",
        "namespace MissionPlanner.GCSViews {\n// new\n}\n",
    );
    f.put("Plugins/example.cs", "class Changed {}\n");
    f.put(
        "GCSViews/NewScreen.cs",
        "namespace MissionPlanner.GCSViews {}\n",
    );
    // Two forms turn out to be resgen output, so the classifier moves them from T2 to T1.
    f.put("GCSViews/FlightData.Designer.cs", STAMPED);
    f.put("Log/lower.designer.cs", STAMPED);
    let out = f.init();
    assert!(text(&out).contains("1 new, 1 flagged"), "{}", text(&out));

    let csv = f.csv();
    let flight = csv
        .lines()
        .find(|l| l.starts_with("GCSViews/FlightData.cs,"))
        .unwrap();
    // Hand columns survive, including a note that needs quoting across two lines.
    for kept in ["mp-gui", "fly-1", "agent-7", ",2,", ",none; the HUD,"] {
        assert!(flight.contains(kept), "lost {kept}: {flight}");
    }
    assert!(csv.contains(
        "\"owner said: keep \"\"as is\"\", for now\nsecond line; upstream-changed: was ported\""
    ));
    // Measured columns follow the file; work in progress goes back to ready.
    assert!(flight.contains(",3,MissionPlanner.GCSViews,"), "{flight}");
    assert!(flight.contains(",ready,"), "{flight}");

    // Untouched work is not flagged; untouched rows are not annotated.
    assert_eq!(f.get("ExtLibs/DroneCAN/DroneCAN.cs", "state"), "ported");
    assert_eq!(f.get("Plugins/example.cs", "notes"), "");
    assert_eq!(f.get("Plugins/example.cs", "state"), "ready");
    // A chosen disposition is kept, through a reclassification too; a default one follows the
    // tier. A new file arrives ready.
    assert_eq!(
        f.get("ExtLibs/Mavlink/MavlinkParse.cs", "disposition"),
        "regenerate"
    );
    assert_eq!(f.get("GCSViews/FlightData.Designer.cs", "tier"), "T1");
    assert_eq!(
        f.get("GCSViews/FlightData.Designer.cs", "disposition"),
        "hand-port"
    );
    assert_eq!(f.get("Log/lower.designer.cs", "tier"), "T1");
    assert_eq!(f.get("Log/lower.designer.cs", "disposition"), "regenerate");
    assert_eq!(f.get("GCSViews/NewScreen.cs", "state"), "ready");

    // And the whole file is still what a refresh of itself produces.
    let once = f.csv();
    f.init();
    assert_eq!(once, f.csv());
}

#[test]
fn refresh_forgets_vanished_rows_only_when_they_hold_no_work() {
    let f = Fixture::new("vanished");
    f.init();
    f.edit("Sizes/s199.cs", &[("owner", "buzz")]);
    fs::remove_file(f.tree().join("Sizes/s199.cs")).unwrap();
    fs::remove_file(f.tree().join("Sizes/m200.cs")).unwrap();
    let out = f.init();
    assert!(text(&out).contains("kept Sizes/s199.cs"), "{}", text(&out));
    let csv = f.csv();
    assert!(csv.contains("\nSizes/s199.cs,"));
    assert!(!csv.contains("\nSizes/m200.cs,"));
    f.check_fails(&["Sizes/s199.cs: no such file in the C# tree"]);
}

#[test]
fn check_passes_on_a_fresh_ledger() {
    let f = Fixture::new("check-ok");
    f.init();
    let text = f.check_passes();
    assert!(text.contains(&format!("{} rows", EXPECTED.len())), "{text}");
}

#[test]
fn check_fails_on_a_file_without_a_row() {
    let f = Fixture::new("check-unlisted");
    f.init();
    f.put("GCSViews/Unlisted.cs", "namespace X {}\n");
    f.check_fails(&["GCSViews/Unlisted.cs: no row"]);
}

#[test]
fn check_fails_on_a_row_without_a_file() {
    let f = Fixture::new("check-orphan");
    f.init();
    fs::remove_file(f.tree().join("Plugins/example.cs")).unwrap();
    f.check_fails(&["Plugins/example.cs: no such file"]);
}

#[test]
fn check_fails_on_a_duplicate_path() {
    let f = Fixture::new("check-duplicate");
    f.init();
    let csv = f.csv();
    let row = csv
        .lines()
        .find(|l| l.starts_with("Plugins/example.cs,"))
        .unwrap();
    fs::write(f.ledger(), csv.replace(row, &format!("{row}\n{row}"))).unwrap();
    f.check_fails(&["Plugins/example.cs: duplicate row"]);
}

#[test]
fn check_fails_on_an_invalid_tier_disposition_or_state() {
    let f = Fixture::new("check-invalid");
    f.init();
    f.edit("Sizes/s199.cs", &[("tier", "T9")]);
    f.edit("Sizes/m200.cs", &[("disposition", "shred")]);
    f.edit("Sizes/m599.cs", &[("state", "finished")]);
    f.edit("Sizes/l600.cs", &[("verification_class", "vibes")]);
    f.check_fails(&[
        "Sizes/s199.cs: invalid tier `T9`",
        "Sizes/m200.cs: invalid disposition `shred`",
        "Sizes/m599.cs: invalid state `finished`",
        "Sizes/l600.cs: invalid verification_class `vibes`",
    ]);
}

#[test]
fn check_fails_on_a_malformed_record() {
    let f = Fixture::new("check-malformed");
    f.init();
    let csv = f
        .csv()
        .replace("\nPlugins/example.cs,", "\nPlugins/example.cs,extra,");
    fs::write(f.ledger(), csv).unwrap();
    f.check_fails(&["21 fields, expected 20"]);
}

/// A done hand-port with everything §6.4 asks for, in a repository that has it.
fn done_row(f: &Fixture) {
    put(&f.repo().join("crates/mp-gui/Cargo.toml"), "[package]\n");
    put(
        &f.repo().join("crates/mp-gui/src/flight_data.rs"),
        "//! Ported from GCSViews/FlightData.cs @ efb0801 (GPL-3.0-only)\n",
    );
    put(&f.repo().join("crates/mp-gui/tests/flight_data.rs"), "\n");
    f.edit(
        "GCSViews/FlightData.cs",
        &[
            ("state", "done"),
            ("target_crate", "mp-gui"),
            (
                "evidence",
                "crates/mp-gui/src/flight_data.rs; crates/mp-gui/tests/flight_data.rs",
            ),
        ],
    );
}

#[test]
fn check_accepts_a_done_row_with_its_evidence() {
    let f = Fixture::new("check-done-ok");
    f.init();
    done_row(&f);
    f.check_passes();
}

#[test]
fn check_fails_on_done_without_evidence() {
    let f = Fixture::new("check-done-bare");
    f.init();
    f.edit("Sizes/s199.cs", &[("state", "done")]);
    f.check_fails(&["Sizes/s199.cs: done without evidence"]);
}

#[test]
fn check_fails_on_done_naming_rust_that_does_not_exist() {
    let f = Fixture::new("check-done-missing");
    f.init();
    done_row(&f);
    fs::remove_file(f.repo().join("crates/mp-gui/tests/flight_data.rs")).unwrap();
    f.edit(
        "ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.cs",
        &[
            ("state", "done"),
            ("target_crate", "mp-chart"),
            ("evidence", "crates/mp-gui/src/flight_data.rs"),
        ],
    );
    f.check_fails(&[
        "GCSViews/FlightData.cs: evidence `crates/mp-gui/tests/flight_data.rs` does not exist",
        "ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.cs: target_crate `mp-chart` does not exist",
    ]);
}

#[test]
fn check_fails_on_a_done_hand_port_without_its_provenance_header() {
    let f = Fixture::new("check-done-provenance");
    f.init();
    done_row(&f);
    put(
        &f.repo().join("crates/mp-gui/src/flight_data.rs"),
        "//! The flight screen.\n",
    );
    f.check_fails(&["GCSViews/FlightData.cs: done, but no Rust file in evidence carries"]);
}

#[test]
fn check_fails_on_dropped_without_a_reason() {
    let f = Fixture::new("check-dropped");
    f.init();
    f.edit("Sizes/s199.cs", &[("state", "dropped")]);
    f.edit(
        "Sizes/m200.cs",
        &[
            ("state", "dropped"),
            ("notes", "owner, 2026-09-24: dead code"),
        ],
    );
    let text = f.check_fails(&["Sizes/s199.cs: dropped without the owner's reason"]);
    assert!(!text.contains("Sizes/m200.cs"), "{text}");
}

#[test]
fn check_fails_on_a_large_port_without_omissions() {
    let f = Fixture::new("check-omissions");
    f.init();
    for path in [
        "Sizes/s199.cs",
        "Sizes/m200.cs",
        "Sizes/l600.cs",
        "Sizes/xl1501.cs",
    ] {
        f.edit(path, &[("state", "ported")]);
    }
    f.edit(
        "Sizes/l1500.cs",
        &[("state", "tested"), ("omissions", "the unused overloads")],
    );
    let text = f.check_fails(&[
        "Sizes/m200.cs: ported with size M but no omissions",
        "Sizes/l600.cs: ported with size L but no omissions",
        "Sizes/xl1501.cs: ported with size XL but no omissions",
    ]);
    assert!(
        !text.contains("Sizes/s199.cs"),
        "S needs no omissions:\n{text}"
    );
    assert!(!text.contains("Sizes/l1500.cs"), "{text}");
}

#[test]
fn check_fails_on_a_file_that_changed_since_the_refresh() {
    let f = Fixture::new("check-stale");
    f.init();
    f.put("Plugins/example.cs", "class Changed {}\n");
    f.check_fails(&["Plugins/example.cs: sha256 is stale"]);
}

#[test]
fn check_without_the_tree_checks_the_csv_alone() {
    let f = Fixture::new("check-no-tree");
    f.init();
    let absent = f.root.join("no-such-tree");
    fs::remove_file(f.tree().join("Plugins/example.cs")).unwrap();

    let out = f.run_with("check", &absent);
    assert!(out.status.success(), "{}", text(&out));
    assert!(text(&out).contains("only the CSV's internal consistency"));

    f.edit("Sizes/s199.cs", &[("state", "finished")]);
    let out = f.run_with("check", &absent);
    assert_eq!(out.status.code(), Some(1));
    assert!(text(&out).contains("Sizes/s199.cs: invalid state"));
}

#[test]
fn status_reports_retired_lines_in_the_plan_shape() {
    let f = Fixture::new("status");
    f.init();
    done_row(&f);
    f.edit("Sizes/l600.cs", &[("state", "dropped"), ("notes", "dead")]);
    f.edit(
        "ExtLibs/ZedGraph/ZedGraph/ZedGraphControl.cs",
        &[("state", "dropped"), ("notes", "mp-chart")],
    );
    f.edit("Sizes/xl1501.cs", &[("state", "reviewed")]);
    let out = f.run("status");
    assert!(out.status.success(), "{}", text(&out));
    let stdout = String::from_utf8_lossy(&out.stdout);
    // T0: ZedGraphControl.cs (2). T3: FlightData.cs (2) done + l600.cs (600) dropped, of every
    // T3 line in the fixture; `reviewed` is not retired.
    let t3_total: usize = EXPECTED
        .iter()
        .filter(|(_, tier)| *tier == "T3")
        .map(|(path, _)| f.get(path, "loc").parse::<usize>().unwrap())
        .sum();
    let t3_total = if t3_total >= 1000 {
        format!("{},{:03}", t3_total / 1000, t3_total % 1000)
    } else {
        t3_total.to_string()
    };
    assert_eq!(
        stdout.lines().next().unwrap(),
        format!("T0 2 retired / T1 0 generated / T2 0 extracted / T3 602 done of {t3_total}")
    );
    assert!(stdout.contains("states: ready "), "{stdout}");
    assert!(stdout.contains(" reviewed 1 done 1 dropped 2"), "{stdout}");
}

/// The committed ledger, against the real C# tree when this machine has it.
#[test]
fn the_real_ledger_passes_check() {
    let repo = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if !repo.join("references/missionplanner").is_dir() {
        println!(
            "https://github.com/ArduPilot/MissionPlanner is absent from references/missionplanner (it is gitignored): checking \
             ledger/ledger.csv's internal consistency only"
        );
    }
    let out = Command::new(env!("CARGO_BIN_EXE_xtask"))
        .args(["ledger", "check"])
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", text(&out));
}
