//! The tier classifier (PLAN.md §4): a pure function of a file's path and its first bytes.
//!
//! Rules are tried in order and the first match wins:
//!
//! 1. **T0 vendored** — under a root in [`VENDORED`]. Every root carries its evidence: listed in
//!    PLAN.md §4.1, or a licence/copyright header, a LICENSE/COPYING/README, or package metadata
//!    naming someone other than Mission Planner. A generated or designer file inside a vendored
//!    library goes with the library: nothing is regenerated or extracted from code that is
//!    deleted.
//! 2. **T1 generated** — a file a generator in the tree emits ([`GENERATED`]), or a
//!    `*.designer.cs` carrying the `<auto-generated>` stamp that resgen, the settings designer
//!    and the Android resource generator all write and the WinForms designer never does. The
//!    stamp, not the file name, decides: `Controls/DefaultSettings.Designer.cs` is a form that
//!    happens to end in `Settings.Designer.cs`.
//! 3. **T4 non-desktop** — the application heads for platforms PLAN.md §1.2 does not target
//!    ([`NON_DESKTOP`]); their fate is the owner's ruling, not a porter's.
//! 4. **T2 designer** — every other `*.designer.cs`: WinForms layout for a form or control.
//! 5. **T3 hand-port** — everything else.

/// Bytes of a designer file searched for the generator's stamp; it is always in the header.
const STAMP_WINDOW: usize = 2048;

/// A tier from PLAN.md §4.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Tier {
    /// Vendored third-party code: deleted, replaced by crates.
    T0,
    /// Machine-generated code: regenerated from the definitions in the tree.
    T1,
    /// WinForms designer output: extracted to a screen spec.
    T2,
    /// Mission Planner's own code: hand-ported.
    T3,
    /// Code for platforms the port does not target: dropped pending the owner's ruling.
    T4,
}

impl Tier {
    /// Every tier, in report order.
    pub const ALL: [Tier; 5] = [Tier::T0, Tier::T1, Tier::T2, Tier::T3, Tier::T4];

    /// The ledger spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            Tier::T0 => "T0",
            Tier::T1 => "T1",
            Tier::T2 => "T2",
            Tier::T3 => "T3",
            Tier::T4 => "T4",
        }
    }

    /// Parses the ledger spelling.
    pub fn parse(s: &str) -> Option<Tier> {
        Tier::ALL.into_iter().find(|t| t.as_str() == s)
    }

    /// What PLAN.md §4 does with a file of this tier. A row may override it (§4.1 allows
    /// hand-porting `MGRS.cs` out of vendored GeoUtility), so this is only the starting value.
    pub fn disposition(self) -> &'static str {
        match self {
            Tier::T0 => "delete",
            Tier::T1 => "regenerate",
            Tier::T2 => "extract",
            Tier::T3 => "hand-port",
            Tier::T4 => "drop-pending-owner",
        }
    }
}

// A path rule is a directory prefix when it ends in `/`, otherwise one exact file. Each carries
// its evidence as a comment beside it, so the rule and the reason cannot drift apart.

/// Third-party trees (T0).
const VENDORED: &[&str] = &[
    "ExtLibs/alglibnet/",                       // PLAN.md §4.1
    "ExtLibs/netDxf/",                          // PLAN.md §4.1
    "ExtLibs/ZedGraph/",                        // PLAN.md §4.1
    "ExtLibs/ObjectListView/",                  // PLAN.md §4.1
    "ExtLibs/DirectShowLib/",                   // PLAN.md §4.1
    "ExtLibs/GMap.NET.Core/",                   // PLAN.md §4.1
    "ExtLibs/GMap.NET.Drawing/",                // PLAN.md §4.1
    "ExtLibs/GMap.NET.WindowsForms/",           // PLAN.md §4.1
    "ExtLibs/ICSharpCode.SharpZipLib/",         // PLAN.md §4.1
    "ExtLibs/BaseClasses/",                     // PLAN.md §4.1
    "ExtLibs/MetaDataExtractorCSharp240d/",     // PLAN.md §4.1
    "ExtLibs/MissionPlanner.Drawing/",          // PLAN.md §4.1, LIB-build scaffolding
    "ExtLibs/MissionPlanner.Drawing.Common/",   // PLAN.md §4.1, LIB-build scaffolding
    "ExtLibs/SvgNet/",                          // PLAN.md §4.1
    "ExtLibs/SharpKml/",                        // PLAN.md §4.1
    "ExtLibs/KMLib/",                           // PLAN.md §4.1
    "ExtLibs/CsAssortedWidgets/",               // PLAN.md §4.1
    "ExtLibs/BSE.Windows.Forms/",               // PLAN.md §4.1
    "ExtLibs/ProjNet/",                         // PLAN.md §4.1
    "ExtLibs/GeoUtility/",                      // PLAN.md §4.1; License.txt
    "ExtLibs/SharpAdbClient/",                  // PLAN.md §4.1
    "ExtLibs/NMEA2000/",                        // PLAN.md §4.1
    "ExtLibs/zlib.net/",                        // PLAN.md §4.1
    "ExtLibs/7zip/",                            // PLAN.md §4.1
    "ExtLibs/NetDFULib/",                       // PLAN.md §4.1, CPOL
    "ExtLibs/Utilities/Matrix.cs",              // PLAN.md §4.1, CPOL header (Philip R. Braica)
    "ExtLibs/Utilities/Kalman3D.cs",            // PLAN.md §4.1, CPOL header (Philip R. Braica)
    "ExtLibs/LibVLC.NET/",                      // COPYING; LGPL-2.1 header, Boris Richter
    "ExtLibs/WinUSBNet/",                       // MIT header, Thomas Bleeker
    "ExtLibs/Zeroconf/", // csproj: Authors Oren Novotny, github.com/onovotny/Zeroconf
    "ExtLibs/LibTessDotNet/", // SGI Free Software License B header
    "ExtLibs/Exocortex.DSP/", // BSD header, Ben Houston
    "ExtLibs/GLControl/", // Open Toolkit Library License header
    "ExtLibs/AviFile/",  // author header, Corinna John
    "ExtLibs/ImageVisualizer/", // LICENSE and README, Aleksander Berus
    "ExtLibs/Comms/System.IO.Ports/", // Mono class library headers, (c) 2006 Novell
    "ExtLibs/Utilities/clipper.cs", // Boost licence header, Angus Johnson
    "ExtLibs/Utilities/fitCurve.cs", // header: from codeproject.com, by Craig Selbert
    "ExtLibs/Utilities/fft.cs", // MIT header, Gerald T. Beauregard
    "ExtLibs/Xamarin.Forms.Platform.WinForms/", // csproj: Copyright Yasuhiro Taniuchi
    "ExtLibs/SkiaSharp.Views.Forms.WinForms/", // AssemblyCopyright Yasuhiro Taniuchi
    "ExtLibs/GeoidHeightsDotNet/", // LICENSE (LGPL-3.0) and README
    // pymavlink's generator (mavgen.py: Copyright Andrew Tridgell); `xtask codegen` replaces it.
    "ExtLibs/Mavlink/pymavlink/",
];

/// Generator output (T1), each with the generator and the input it reads.
const GENERATED: &[&str] = &[
    // mavgen --lang=CS over message_definitions/*.xml, per regenerate.bat. mavgen also copies
    // fixed .cs files beside it, but regenerate.bat takes only mavlink.cs and MP's copies have
    // since diverged from the templates, so those are hand-maintained (T3).
    "ExtLibs/Mavlink/Mavlink.cs",
    "ExtLibs/DroneCAN/out/", // canard_dsdlc.py over dsdl/**.uavcan: include/ and src/
    "ExtLibs/DroneCAN/canard_dsdlc/messages.cs", // canard_dsdlc.py: open('messages.cs', 'w')
    "ExtLibs/WebAPIs/Dowding/src/", // swagger-codegen 2.2.1 over dowdingswagger.json
    "ExtLibs/WebAPIs/Dronelogbook/src/", // swagger-codegen 2.2.1 over swagger.json
];

/// Application heads for platforms PLAN.md §1.2 lists as non-goals (T4).
const NON_DESKTOP: &[&str] = &[
    "ExtLibs/Xamarin/",                // PLAN.md §4 T4: the Xamarin Android/iOS app
    "ExtLibs/uno/",                    // Uno Platform heads: Droid, iOS, UWP, Wasm
    "ExtLibs/wasm/",                   // Blazor WebAssembly head; browser GCS is a §1.2 non-goal
    "ExtLibs/UsbSerialForAndroid/",    // Android-only USB serial binding
    "ExtLibs/System.Drawing.android/", // System.Drawing for Android
];

fn matches(roots: &[&str], path: &str) -> bool {
    roots.iter().any(|root| {
        if root.ends_with('/') {
            path.starts_with(root)
        } else {
            path == *root
        }
    })
}

fn is_designer(path: &str) -> bool {
    // Both spellings occur in the tree (`Resource.designer.cs` is the Android generator's).
    path.to_ascii_lowercase().ends_with(".designer.cs")
}

/// Classifies one file. `path` is relative to the C# root with `/` separators; `content` is the
/// file's bytes (only the head of a designer file is looked at).
pub fn classify(path: &str, content: &[u8]) -> Tier {
    if matches(VENDORED, path) {
        return Tier::T0;
    }
    if matches(GENERATED, path) || (is_designer(path) && has_generator_stamp(content)) {
        return Tier::T1;
    }
    if matches(NON_DESKTOP, path) {
        return Tier::T4;
    }
    if is_designer(path) {
        return Tier::T2;
    }
    Tier::T3
}

fn has_generator_stamp(content: &[u8]) -> bool {
    let head = content.get(..STAMP_WINDOW).unwrap_or(content);
    head.windows(b"<auto-generated".len())
        .any(|w| w == b"<auto-generated")
}
