# Generated by `cargo xtask codegen-resx` from ExtLibs/Strings/Strings.ja-JP.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 136 of 185 keys.

BadCoords = 無効な緯度/経度
CannotGraphField = このフィールドにグラフを描けません
CommandFailed = コマンドの実行に失敗しました
    {""}
ERROR = エラー
ErrorClosingLogFile = ログファイルのクローズエラー
ErrorCommunicating = オートパイロットとの通信エラー
ErrorConnecting = 接続エラー
    {""}
ErrorFeatureNotEnabled = 今のファームウェアではこの機能は無効です
ErrorFirmwareFile = ファームウェア ファイルの読込エラー
ErrorLogList = ログリストの取得エラー
ErrorNoResponse = エラー: MAVからの応答がありません
ErrorNotConnected = 接続していません
ErrorReceivingParams = リストの取得エラー
ErrorRejectedByMAV = エラー: コマンドが拒絶されました by MAV
ErrorRenameFile = ファイル名変更エラー
ErrorSettingParameter = 設定パラメータのエラー
ErrorSetValueFailed = セット { $arg0 } 失敗
InvalidAlt = 高度が無効
InvalidBaudRate = ボーレートが無効
InvalidField = フィールドが無効
InvalidFileName = ファイル名が無効です
InvalidNumberEntered = 入力値が無効
InvalidPanRange = パンの範囲が無効です
InvalidPortName = ポート名が無効です
InvalidTiltRange = チルト範囲が無効です
InvalidUpdateRate = レートのアップデートが無効
NoFMTMessage = FMTメッセージがありません for{" "}
PleaseConnect = まず最初に接続してください
PleaseLoadValidFile = 有効なファイルをロードしてください
PleaseSelectCell = 最初にセル数を選択
SelectComport = COMポートを選択してください
WarningLogBrowseFMTMissing = ログブラウズは、ログ内のFMTメッセージなしでは正常に機能しません。
    これらはログから欠落しているように見えます。
    {""}
WarningUpdateParamList = パラメータのアップデート
    機体が空中にある場合には実行しないでください！
Checking = チェック中
DownloadedFromInternet = インターネットからダウンロードしたもの
Getting = 取得中
GettingUpdatedParams = アップデートされたパラメータの取得中
AdvancedParams = アドバンスト パラメータ
BasicTuning = ベーシック チューニング
Desc = 説明:{" "}
ExtendedTuning = 拡張チューニング
FlightModes = フライト モード
FullParameterList = フルパラメータ リスト
FullParameterTree = フルパラメータ ツリー
GeoFence = ジオ フェンス
StandardParams = スタンダード パラメータ
Units = 単位: { $arg0 }{ $arg1 }
ProgrammedOK = 書込成功
CONNECTc = 接続
Disconnect = 切断
DISCONNECTc = 切断
Failclog = ログの生成に失敗しました - このセッションはログ保存されません
NewFirmware = 新しいファームウェア
NewFirmwareA = 新たしいファームウェアが使用可能です
Pleaseup = {""}
    アップグレードしてください
Stillmoving = 機体がまだ動いていますが、切断してよろしいですか？
Timeout = オートスキャンの待受がタイムアウトしました/Mavlinkデバイスがありません
ConnectFailed = 接続失敗しました
ConnectingMavlink = Mavlink接続中
Done = 終了
GettingParams = パラメータ取得中
GettingParamsD = パラメータ取得中...
Gotparam = 取得したパラメータ
MavlinkConnecting = Mavlink 接続中...
Only1Hb = ハートビートを１回だけ受信しました
Only1HbD = 1つだけの Mavlinkハートビートパケットがこのポートから読み取られました - ハードウェアが正常に設定されているか確認してください
    ミッションプランナーは、接続する前に2つの有効なハートビートパケットを待ちます
Trying = 接続試行中.
    タイムアウト { $arg0 }
CantDetectBoardVersion = 基板のバージョンが検出できません．接続を確認して下さい．
CheckPortSettingsOr = ポート設定をチェックしてください/またはポートが使用中？
CommunicationErrorNoConnection = 通信エラー - 接続がありません
DetectedA = 検出：
DetectingBoardVersion = ボードのバージョンを検出中
DownloadingFromInternet = インターネットからダウンロード
EppromChanged = EEPROMが変更されました.アップデートするとすべてのセッティングは失われます．
    続行しますか？
EppromFormatChanged = EEPROMフォーマットが変更されました ({"{"}0) vs { $arg1 })
FailedDownload = ダウンロード失敗
FailedReadHEX = HEXの読込に失敗しました
FailedToReadHex = ファームウェア.hexの読込に失敗しました
FailedUpload = アップロードに失敗しました
GettingFWList = FW リスト取得中
GettingFWVersion = ファームウェアバージョンを取得中
InvalidBoardType = 基板タイプが無効
PleaseConnectAndBackupConfig = コンフィグタブの中で接続し，設定のバックアップを取ってください
ReadingHexFile = Hexファイルを読み込んでいます
ReceivedList = 受信したリスト
UploadComplete = アップロード完了
UploadingBytesToBoard = アップロード中 { $arg0 } バイトを基板へ:
VerifyComplete = ベリファイ 完了
VerifyFirmware = ファームウェアのベリファイ
UploadSucceededButVerifyFailed = アップロード成功，しかしベリファイ失敗: exp { $arg0 } got { $arg1 } at{" "}
    {""}
ReadingHex = Hexを読込中
Warningrallypointdistance = 警告：ラリーポイントがRALLY_LIMIT_KMよりも大きくなっています
Warning = 警告
WarningAC32 = 警告：もしAC3.2以上を初めてインストールしたなら、コンパスキャリブレーションを必ず実行してください．
WarningAC31 = 警告：AC3.1ではモータはARMEDすると回転しますが，MOT_SPIN_ARMEDパラメータで変更できます
MagCalibMsg = OKをクリックし、オートパイロットを各軸まわりに回転させてください。
MissingDataPoints = データポイントが失われます．それでもキャリブレーションを実行しますか？
RunAnyway = ともかく実行
UpdateFound = アップデートが見つかりました
    {""}
    今アップデートしますか？ [link;
UpdateNow = 今アップデート
RawParamWarning = 生のパラメータに警告
RawParamWarningi = 画面上のすべての値は最大最小値がチェックされません．入力値はダブルチェックしてください．
    安全な設定のためにスタンダード/アドバンストパラメータを使用してください．
ShowMeAgain = もう一度表示しますか？
OK = OK
LinkStats = 統計データにリンク
Stop = ストップ
Connect = 接続
Start = スタート
AreYouSureYouWantToUpload = アップロードしてよろしいですか？
Beta = ベータ版
BetaWarning = これはベータ版のファームウェアのため、使用にはリスクがあります！
CanNotConnectToComPortAnd = COMポートに接続し、基板を検出できません
Continue = 続ける
ErrorUploadingFirmware = ファームウェアのアップロード失敗
QuestionMark = ?
Trunk = trunk
TrunkWarning = これらは最新のファームウェアです。使用にはリスクがあります！
BadGPSHealth = GPS状態異常
BadGyroHealth = ジャイロに異常あり
BadAccelHealth = 加速度の状態異常
BadCompassHealth = コンパスに異常あり
BadBaroHealth = 気圧センサ異常
BadLiDARHealth = LiDARの状態異常
BadOptFlowHealth = OptFlowに異常あり
BadorNoTerrainData = 異常,または地形データが無い
GeofenceBreach = ジオ フェンス違反
BadAHRS = AHRS異常
NORCReceiver = RC受信機がありません
AutoWP = Auto WP
EnsurePropsNotOn = 機体にプロペラを付けていないことを確認して下さい
FailSafe = フェイルセーフ
Error_binding = バインディング エラー
Put_the_transmitter_in_bind_mode__Receiver_is_waiting = 送信機をバインドモードにしてください．受信機が待っています．
Completed = 完了
Click_when_Done = 完了したらクリック
Saving = 保存中
