# Generated by `cargo xtask codegen-resx` from ExtLibs/Strings/Strings.de-DE.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 3 of 185 keys.

ThisBoardHasBeenRetired = This board has been retired, Mission Planner this will upload the last available version to your board
ZeroAltWarningCopter = WP# { $arg0 } hat eine Höhe von null, d. h. keine Höhenänderung! Wenn Sie eine Höhe von null wünschen, ändern Sie sie auf 0,01 m. Möchten Sie den WP-Upload fortsetzen oder abbrechen?
ZeroAltWarningTitle = Warnung vor Nullhöhe
