# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.zh-Hans.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 64 of 135 keys, and 2 orphan(s) the base file no longer has.

flightdata-recordHudToAVIToolStripMenuItem-Text = 录制Hud至AVI
flightdata-stopRecordToolStripMenuItem-Text = 停止记录
flightdata-setMJPEGSourceToolStripMenuItem-Text = 设置MJPEG源
flightdata-setAspectRatioToolStripMenuItem-Text = 设置宽高比
flightdata-userItemsToolStripMenuItem-Text = 使用项目
flightdata-russianHudToolStripMenuItem-Text = 俄国Hud
flightdata-tabQuick-Text = 快速
flightdata-BUT_resumemis-Text = 恢复任务
flightdata-BUT_mountmode-Text = 设置挂载
flightdata-BUT_ARM-Text = 解锁/锁定
flightdata-BUT_joystick-Text = 游戏
    摇杆
flightdata-BUT_quickmanual-Text = 手动
flightdata-BUT_quickrtl-Text = 返航
flightdata-BUT_quickauto-Text = 自动
flightdata-BUT_setwp-Text = 设定航点
flightdata-BUT_setmode-Text = 设置模式
flightdata-BUT_clear_track-Text = 清除轨迹
flightdata-BUT_Homealt-Text = 设置
    家的高度
flightdata-BUT_RAWSensor-Text = 原始传感器查看
flightdata-BUTrestartmission-Text = 重新开始
    任务
flightdata-BUTactiondo-Text = 执行动作
flightdata-tabActions-Text = 动作
flightdata-myButton1-Text = 留待
flightdata-myButton2-Text = 返航
flightdata-myButton3-Text = 自动
flightdata-tabActionsSimple-Text = 简单动作
flightdata-tabPagePreFlight-Text = 起飞前检查
flightdata-tabGauges-Text = 仪表
flightdata-tabStatus-Text = 状态
flightdata-tabServo-Text = 舵机
flightdata-BUT_loadtelem-Text = 加载日志
flightdata-BUT_log2kml-Text = Tlog > Kml 或图像
flightdata-BUT_playlog-Text = 播放/暂停
flightdata-label2-Text = 速度
flightdata-tabTLogs-Text = 遥测日志
flightdata-BUT_loganalysis-Text = 自动分析
flightdata-BUT_DFMavlink-Text = 通过Mavlink
    下载闪存日志
flightdata-but_dflogtokml-Text = 创建KML + gpx
flightdata-but_bintolog-Text = PX4 .Bin 转 .Log
flightdata-BUT_matlab-Text = 创建Matlab文件
flightdata-BUT_logbrowse-Text = 回顾日志
flightdata-tablogbrowse-Text = 数据闪存日志
flightdata-checkBoxRedirectOutput-Text = 重定向程序输出
flightdata-BUT_edit_selected-Text = 编辑所选脚本
flightdata-labelSelectedScript-Text = 所选脚本：无
flightdata-BUT_run_script-Text = 运行脚本
flightdata-BUT_abort_script-Text = 忽略运行中的脚本
flightdata-labelScriptStatus-Text = 脚本状态：没有脚本正在运行
flightdata-BUT_select_script-Text = 选择脚本
flightdata-tabScripts-Text = 脚本
flightdata-tabPagemessages-Text = 消息
flightdata-goHereToolStripMenuItem-Text = 飞行至此
flightdata-flyToHereAltToolStripMenuItem-Text = 飞行至此高度
flightdata-pointCameraHereToolStripMenuItem-Text = 在此放置相机
flightdata-triggerCameraToolStripMenuItem-Text = 现在按下相机快门
flightdata-flightPlannerToolStripMenuItem-Text = 飞行规划器
flightdata-setHomeHereToolStripMenuItem-Text = 设置家在此
flightdata-label6-Text = GPS追踪（黑）
flightdata-label5-Text = 目标指向
flightdata-label3-Text = 直达当前航点
flightdata-label4-Text = 当前指向
flightdata-label1-Text = 缩放
flightdata-CHK_autopan-Text = 自动平移
flightdata-CB_tuning-Text = 调试
# orphan: no entry `dataGridViewImageColumn1.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn1-HeaderText = 上
# orphan: no entry `dataGridViewImageColumn2.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn2-HeaderText = 下
