# Generated by `cargo xtask codegen-resx` from ExtLibs/Strings/Strings.zh-Hans.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 144 of 185 keys.

BadCoords = 有问题的经度/纬度
CannotGraphField = 不能绘制这一区域
CommandFailed = 命令执行失败
    {""}
ERROR = 错误
ErrorClosingLogFile = 关闭日志文件时错误
ErrorCommunicating = 与自动驾驶仪通讯时错误
ErrorConnecting = 连接错误
    {""}
ErrorFeatureNotEnabled = 这个功能在您的固件没有启用
ErrorFirmwareFile = 加载固件时错误
ErrorLogList = 接收日志列表时错误
ErrorNoResponse = 错误: 没有来自飞行器的响应
ErrorNotConnected = 您还没有连接。
ErrorReceivingParams = 接收列表时错误
    {""}
ErrorRejectedByMAV = 错误: 飞行器拒绝了命令
ErrorRenameFile = 重命名文件时出错
ErrorSettingParameter = 设置参数时出错
ErrorSetValueFailed = 设置 { $arg0 } 失败
InvalidAlt = 无效的高度
InvalidBaudRate = 无效的波特率
InvalidField = 无效的 Field
InvalidFileName = 无效的文件名
InvalidNumberEntered = 输入的数字无效
    {""}
InvalidPanRange = 无效的 Pan 范围
InvalidPortName = 无效的串口名
InvalidTiltRange = 无效的倾斜范围
InvalidUpdateRate = 无效的刷新率
NoFMTMessage = 没有格式(FMT)信息 for
PleaseConnect = 请先连接
PleaseLoadValidFile = 请加载一个有效的文件
PleaseSelectCell = Please select a cell first
SelectComport = 请先选择一个串口
WarningLogBrowseFMTMissing = 日志浏览因您的日志中没有格式(FMT)信息而不能正确工作。
    这些似乎是从您的日志里丢失的。
WarningUpdateParamList = 更新参数
    如果您的载具在空中，请不要这么做！
    {""}
Checking = 正在检查{" "}
DownloadedFromInternet = 下载完毕
Getting = 正在获取{" "}
GettingUpdatedParams = 正在获取更新的参数列表
AdvancedParams = 高级参数
BasicTuning = 基本调参
Desc = 描述：
ExtendedTuning = 扩展调参
FlightModes = 飞行模式
FullParameterList = 全部参数表
FullParameterTree = 全部参数树
GeoFence = 地理围栏
StandardParams = 标准参数
Units = 单位：{ $arg0 }{ $arg1 }
CONNECTc = 连接
Disconnect = 断开连接
DISCONNECTc = 断开连接
Failclog = 创建日志失败 - 将不会记录本次会话
NewFirmware = 新固件
NewFirmwareA = 有新固件可用
    {""}
Pleaseup = {""}
    请升级
Stillmoving = 您的模型仍然在移动，确认断开连接？
Timeout = 自动扫描超时或者没有mavlink设备
ConnectFailed = 连接失败
ConnectingMavlink = 正在连接Mavlink
Done = 完成
GettingParams = 正在获取参数
GettingParamsD = 正在获取参数...
Gotparam = 获得参数{" "}
MavlinkConnecting = Mavlink 正在连接...
Only1Hb = 只接收到一次Heartbeat
Only1HbD = Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
    Mission Planner waits for 2 valid heartbeat packets before connecting
Trying = 尝试连接。
    在{ $arg0 }秒后超时
CantDetectBoardVersion = 不能检测到您控制板的版本。 请检查连接
CheckPortSettingsOr = 检查端口设置或者正在使用端口？
CommunicationErrorNoConnection = 通信错误 - 没有连接
DetectedA = 检测到一个
DetectingBoardVersion = 正在检测控制板的版本
DownloadingFromInternet = 正在下载
EppromChanged = Epprom更改了, 您所有的设置将在更新中丢失,
    您希望继续吗？
EppromFormatChanged = Epprom格式已更改 ({"{"}0) vs { $arg1 })
FailedDownload = 下载失败
FailedReadHEX = 读取十六进制文件失败
FailedToReadHex = 读取firmware.hex失败 :
FailedUpload = 上传失败
GettingFWList = 正在获取固件列表
GettingFWVersion = 正在获取固件版本
InvalidBoardType = 无效的控制板类型
PleaseConnectAndBackupConfig = 请在配置选项卡连接并备份配置。
ReadingHexFile = 正在读取十六进制文件
ReceivedList = 获取列表完成
UploadComplete = 上传完成
UploadingBytesToBoard = 正在上传 { $arg0 }字节 到您的控制板
VerifyComplete = 校验完成
VerifyFirmware = 校验固件
UploadSucceededButVerifyFailed = 上传成功，但是校验失败: 输出 { $arg0 } 获得 { $arg1 } 位于{" "}
ReadingHex = 正在读取十六进制文件
Warningrallypointdistance = 警告，集结点放置在了比RALLY_LIMIT_KM还大的地方
Warning = 警告
WarningAC32 = 警告，如果您是第一次安装AC 3.2，您“必须”重做一次罗盘校准。
WarningAC31 = 警告，从AC 3.1起，电机将在解锁后转动，这可以通过MOT_SPIN_ARMED参数配置
MagCalibMsg = 请单击确认并且将自动驾驶仪绕所有轴做圆周运动
MissingDataPoints = 还缺少数据点。您无论如何也想结束校准吗？
RunAnyway = 非要运行
UpdateFound = 发现更新
    {""}
    您希望现在更新吗？ [link;
UpdateNow = 现在更新
RawParamWarning = 原始参数警告
RawParamWarningi = 本页面所有的值都不会进行大小检查。请再三检查您输入的值。
    如想安全地设置，请使用标准/高级参数
ShowMeAgain = 再次显示？
OK = 好的
LinkStats = 链接统计
Stop = 停止
Connect = 连接
Start = 开始
AreYouSureYouWantToUpload = 您确认要升级到
Beta = 测试版
BetaWarning = 这些是测试版固件，请您自担风险！！！
CanNotConnectToComPortAnd = 不能连接COM口检测控制板类型
Continue = 继续
ErrorUploadingFirmware = 上载固件错误
QuestionMark = 吗？
Trunk = 主干分支
TrunkWarning = 这些是最新的主干分支（开发版）固件，请您自担风险！！！
AutoWP = 自动航点
EnsurePropsNotOn = 确保飞行器没有安装螺旋桨
FailSafe = 故障保护
Error_binding = 对频错误
Put_the_transmitter_in_bind_mode__Receiver_is_waiting = 请将发射机置于对频(bind)模式。接收机正在等待。
Completed = 完成
Click_when_Done = 完成时点击
Saving = 保存中
InvalidCert = 证书无效
Note = 注意
PleaseUnplugTheBoardAnd = 请拔下控制板，点击OK后再插入。
    Mission Planner将会在30秒内寻找控制板。
ThisBoardHasBeenRetired = 此控制板已经退出历史舞台了，Mission Planner将会上传最后一个支持的版本到您控制板。
YouAreUsingUnsupportedHardware = 您正在使用不受支持的硬件。
    此控制板没有包含真伪性的有效证书。
    请就为您的硬件签名联系您的硬件提供商。
NoNeedToUpload = 无需上传。当前固件已经安装在控制板上。
PleaseWaitForTheMusicalTones = 请在音乐播放完后再点击OK。
ObtainFromModule = 从模块获取
SetHere = 设置在这
TrackerHome = 追踪器的家
velocity_variance = velocity variance
compass_variance = compass variance
pos_horiz_variance = pos horiz variance
pos_vert_variance = pos vert variance
terrain_alt_variance = 地形高度差异
ChangeThrottle = 更改油门
Invalid_home_location = 无效的家位置
Converting_bin_to_log = 转换bin文件到log文件
UpdateNotFound = 没有可用更新
Failed_to_connect_to_SITL_instance = 无法连接到SITL实例
