# Generated by `cargo xtask codegen-resx` from ExtLibs/Strings/Strings.uk.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 184 of 185 keys.

BadCoords = Невірні Широта/Довгота
CannotGraphField = Неможливо створити графік цього поля
CommandFailed = Не вдалося виконати команду
    {""}
ERROR = Помилка
ErrorClosingLogFile = Помилка при закритті лог-файлів
ErrorCommunicating = Помилка зв'язку з автопілотом
ErrorConnecting = Помилка під'єднання
    {""}
ErrorFeatureNotEnabled = Ця функція не активована у вашій прошивці.
ErrorFirmwareFile = Помилка при завантаженні файлу прошивки
ErrorLogList = Помилка при отриманні списку лог-файлів
ErrorNoResponse = Помилка: М-БпЛА не відповідає
ErrorNotConnected = Ви не під'єднані.
ErrorReceivingParams = Помилка при отриманні списку
    {""}
ErrorRejectedByMAV = Помилка: М-БпЛА відхилив команду
ErrorRenameFile = Помилка перейменування файлу
ErrorSettingParameter = Помилка при встановленні параметру{" "}
ErrorSetValueFailed = Не вдалося встановити { $arg0 }
InvalidAlt = Невірна висота
InvalidBaudRate = Невірна швидкість передачі даних
InvalidField = Невірне Поле
InvalidFileName = Невірна назва файлу
InvalidNumberEntered = Невірне введене число
    {""}
InvalidPanRange = Невірний діапазон Панорамування
InvalidPortName = Невірна назва порта
InvalidTiltRange = Невірний діапазон Нахилу
InvalidUpdateRate = Невірна частота оновлень
NoFMTMessage = Немає FMT-повідомлення для{" "}
PleaseConnect = Спочатку під'єднайтесь, будь ласка
PleaseLoadValidFile = Завантажте дійсний файл, будь ласка
PleaseSelectCell = Спочатку оберіть клітинку, будь ласка
SelectComport = Оберіть COM-порт, будь ласка
WarningLogBrowseFMTMissing = Перегляд журналу не може працювати належним чином без FMT-повідомлень у
    вашому журналі. Здається, що вони відсутні у вашому журналі.
WarningUpdateParamList = Оновити Параметри
    НЕ РОБІТЬ ЦЬОГО У ПОВІТРІ
    {""}
Checking = Перевірка{" "}
DownloadedFromInternet = Завантажено з інтернету
Getting = Отримання{" "}
GettingUpdatedParams = Отримання оновлених параметрів
AdvancedParams = Розширені параметри
BasicTuning = Базове Налаштування
Desc = Опис:{" "}
ExtendedTuning = Розширене налаштування
FlightModes = Режими польоту
FullParameterList = Список параметрів
FullParameterTree = Дерево параметрів
GeoFence = Геозона
StandardParams = Стандартні параметри
Units = Одиниці: { $arg0 }{ $arg1 }
ProgrammedOK = Програмування успішне
CONNECTc = ПІД'ЄДНАТИСЬ
Disconnect = Роз'єднатись
DISCONNECTc = РОЗ'ЄДНАТИСЬ
Failclog = Не вдалося створити журнал наземної станції - тому дані
    про цю сесію не будуть записуватись
NewFirmware = Нова прошивка
NewFirmwareA = Доступна нова прошивка
    {""}
Pleaseup = {""}
    Будь ласка, зробіть апгрейд
Stillmoving = Ваш апарат ДОСІ РУХАЄТЬСЯ - ви впевнені, що хочете РОЗ'ЄДНАТИСЬ?
Timeout = Час очікування на автосканер вийшов/Пристрій MAVLink не під'єднаний
ConnectFailed = Не вдалося під'єднатись
ConnectingMavlink = Під'єднується MAVLink
Done = Готово
GettingParams = Отримання параметрів
GettingParamsD = Отримання параметрів...
Gotparam = Отримав параметр{" "}
MavlinkConnecting = MAVLink під'єднується...
Only1Hb = Отримано лише 1 серцебиття
Only1HbD = Було зчитано лише 1 серцебиття MAVLink з порта. Переконайтеся, що ваше обладнання вірно налаштовано.
    MissionPlanner очікує на дійсних 2 серцебиття перед під'єднанням
Trying = Спроба під'єднатись
    Час очікування { $arg0 }
CantDetectBoardVersion = Не вдається визначити версію Вашої плати. Перевірте кабель.
CheckPortSettingsOr = Налаштування невірні або порт вже використовується?
CommunicationErrorNoConnection = Помилка зв'язку - немає під'єднання
DetectedA = Визначено{" "}
DetectingBoardVersion = Визначення версії плати
DownloadingFromInternet = Завантаження з Інтернету
EppromChanged = EEPROM змінено. Під час оновлення будуть втрачені усі ваші налаштування.
    Бажаєте продовжити?
EppromFormatChanged = Формат EEPROM змінено ({"{"}0) проти { $arg1 })
FailedDownload = Не вдалося завантажити
FailedReadHEX = Не вдалося зчитати HEX-файл
FailedToReadHex = Не вдалося зчитати файл firmware.hex :
FailedUpload = Не вдалося завантажити
GettingFWList = Отримання списку прошивок
GettingFWVersion = Отримання версії прошивки
InvalidBoardType = Невірний тип плати
PleaseConnectAndBackupConfig = Будь ласка, під'єднайтесь та створіть резервну копію конфігурації на вкладці конфігурації.
ReadingHexFile = Зчитання HEX-файлу
ReceivedList = Список отримано
UploadComplete = Завантаження завершено
UploadingBytesToBoard = Завантаження { $arg0 } байт на Плату:
VerifyComplete = Перевірку завершено
VerifyFirmware = Перевірка прошивки
UploadSucceededButVerifyFailed = Завантаження успішне, але перевірка невдала: очікував { $arg0 } отримав { $arg1 } у{" "}
ReadingHex = Зчитання HEX
Warningrallypointdistance = ПОПЕРЕДЖЕННЯ! Точки пунктів збору розташовані вище ніж обмеження RALLY_LIMIT_KM
Warning = ПОПЕРЕДЖЕННЯ
WarningAC32 = ПОПЕРЕДЖЕННЯ! Якщо ви встановлюєте AC 3.2 вперше, то ви ПОВИННІ повторити калібрування компасу.
WarningAC31 = ПОПЕРЕДЖЕННЯ! Починаючи з версії AC 3.1, мотори обертатимуться коли розблоковані. Це можна налаштувати
    через параметр MOT_SPIN_ARMED
MagCalibMsg = Будь ласка, натисніть OK та перемістіть автопілот круговими рухами навколо всіх осей
MissingDataPoints = Ви не вказали точок даних. Ви все одно хочете запустити калібрацію?
RunAnyway = все одно запустити
UpdateFound = Знайдено оновленя
    {""}
    Чи хочете оновитись зараз?{" "}
UpdateNow = Оновитись зараз
RawParamWarning = ПОПЕРЕДЖЕННЯ про параметри, які не перевірятимуться
RawParamWarningi = Усі значення на цьому екрані не перевірятимуться на перевищення мін/макс обмежень.
    Тому, будь ласка, двічи перевірте введені дані. Радимо використовувати Стандартні
    чи Розширені параметри для безпечних налаштувань.
ShowMeAgain = Показувати ще раз?
OK = OK
LinkStats = Статистика під'єднання
Stop = Стоп
Connect = Під'єднатись
Start = Старт
AreYouSureYouWantToUpload = Чи ви впевнені, що хочете завантажити{" "}
Beta = Beta
BetaWarning = Ця прошивка - у Beta-версії, використовуйте на власний ризик!!!
CanNotConnectToComPortAnd = Не вдається під'єднатись до COM-порта та визначити тип плати
Continue = Продовжити
ErrorUploadingFirmware = Помилка при завантаженні прошивки
QuestionMark = ?
Trunk = trunk
TrunkWarning = Це trunk-версія прошивки та може містити найновіший та непротестований код,
    використовуйте на власний ризик!!!
BadGPSHealth = Неякісні дані GPS
BadAirspeed = Несправний сенсор Повітр. швидкості
BadGyroHealth = Несправний Гіроскоп
BadAccelHealth = Несправний Аксел.
BadCompassHealth = Несправний компас
BadBaroHealth = Несправний барометр
BadLiDARHealth = Несправний ЛІДАР
BadOptFlowHealth = Несправний Оптичний потік
BadorNoTerrainData = Дані про ландшафт недійсні або їх немає
GeofenceBreach = Порушення Геозони
BadAHRS = Несправна курсовертикаль
NORCReceiver = НЕМАЄ RC-приймача
AutoWP = Автом.пункт маршр.
EnsurePropsNotOn = ПЕРЕКОНАЙТЕСЯ, що на М-БпЛА НЕ встановлені гвинти
FailSafe = Failsafe
Error_binding = Помилка прив'язки
Put_the_transmitter_in_bind_mode__Receiver_is_waiting = Переведіть передавач у режим прив'язки. Приймач чекає.
Completed = Завершено
Click_when_Done = Клікніть після Завершення
Saving = Збереження
InvalidCert = Невірний сертифікат
Note = Примітка
PleaseUnplugTheBoardAnd = Будь ласка, фізично від'єднайте плату та натисніть OK, потім
    знов приєднайте її. Програма спробує знайти плату протягом 30 секунд.
ThisBoardHasBeenRetired = Ця плата була знята з експлуатації. Програма завантажить найновішу версію на вашу плату (AC 3.2.1/AP 3.4.0)
YouAreUsingUnsupportedHardware = Ви використовуєте непідтримуване обладнання.
    Ця плата не містить дійсного сертифікату автентичності.
    Зв'яжіться зі своїм постачальником з цього питання.
NoNeedToUpload = Немає потреби у завантаженні - тому що вже є на платі
PleaseWaitForTheMusicalTones = Перш ніж натискати OK, спочатку дочекайтеся доки музична мелодія не закінчиться
ObtainFromModule = Завантажити з модуля
SetHere = Вказати тут
TrackerHome = Tracker Home
velocity_variance = дисперсія швидкості
compass_variance = дисперсія компаса
pos_horiz_variance = дисперсія по горизонталі
pos_vert_variance = дисперсія по вертикалі
terrain_alt_variance = дисперсія висот ландшафту
ChangeThrottle = Змінити газ
Invalid_home_location = Невірне місце для дом.точки
Converting_bin_to_log = Перетворення даних у журнал
UpdateNotFound = Немає доступного оновлення.
Failed_to_connect_to_SITL_instance = Не вдалося під'єднатись до екземпляру SITL
Scanning_File = Сканування файлу
Zoom_to_the_center_or_the_loaded_file = Збільшити центр чи завантажений файл?
Zoom_To = Збільшити точку
Do_you_want_to_load_this_into_the_flight_data_screen = Бажаєте завантажити це на екран даних польоту?
Load_data = Завантажити дані
Bad_KML_File = Невірний KML-файл :
No_valid_heartbeats_read_from_port = З порта не було зчитано жодного дійсного серцебиття
Bad_Vision_Position = Невірне положення для візуального позиціювання
BadLogging = Журнал записів невірний
ParamRefreshRequired = "Потребується оновлення параметру - натисніть F5.
    було #{ $arg0 }  стало #{ $arg1 }"
Failed_to_download_the_SITL_image = Не вдалося завантажити образ SITL.
Not_available_when_used_as_a_windows_store_app = Недоступно коли використовується як Windows Store додаток
No_firmware_available_for_this_board = Для цієї плати немає прошивки!
OnboardOSD = Екранний дисплей
User_Params = Параметри користувача
Planner = Планувальник
Cancel = Скасувати
No_valid_sik_radio = Немає дійсної SiK-радіостанції
MAVFtp = MAVFtp
Bad_Battery = Несправна батарея
Bad_Proximity = Невірне значення близькості
Bad_SatCom = Несправний зв'язок зі супутником
Prearm_check_failed = Попередня перевірка безпеки при розблокуванні НЕВДАЛА
    - перегляньте повідомлення
Invalid_Location = Невірне значення місцезнаходження
Loading = Завантаження
ZeroAltWarningCopter = WP# { $arg0 } має нульову висоту, це означає відсутність змін висоти! Якщо вам потрібна нульова висота, змініть її на 0,01 м. Продовжити чи скасувати завантаження wp?
ZeroAltWarningTitle = Попередження про нульову висоту
