# Generated by `cargo xtask codegen-resx` from ExtLibs/Strings/Strings.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 185 of 185 keys.

BadCoords = Bad Lat/Lng
CannotGraphField = Cannot graph this field
CommandFailed = The Command failed to execute
    {""}
ERROR = Error
ErrorClosingLogFile = Error closing log files
ErrorCommunicating = Error communicating with the autopilot
ErrorConnecting = Error Connecting
    {""}
ErrorFeatureNotEnabled = This feature is not enabled in your firmware.
ErrorFirmwareFile = Error loading firmware file
ErrorLogList = Error receiving log list
ErrorNoResponse = Error: no response from MAV
ErrorNotConnected = You are not connected.
ErrorReceivingParams = Error receiving list
    {""}
ErrorRejectedByMAV = Error: command rejected by MAV
ErrorRenameFile = Error renaming file
ErrorSettingParameter = Error setting parameter{" "}
ErrorSetValueFailed = Set { $arg0 } Failed
InvalidAlt = Invalid Alt
InvalidBaudRate = Invalid BaudRate
InvalidField = Invalid Field
InvalidFileName = Invalid FileName
InvalidNumberEntered = Invalid number entered
    {""}
InvalidPanRange = Invalid Pan Range
InvalidPortName = Invalid PortName
InvalidTiltRange = Invalid Tilt Range
InvalidUpdateRate = Invalid Update Rate
NoFMTMessage = No FMT message for{" "}
PleaseConnect = Please connect first
PleaseLoadValidFile = Please load a valid file
PleaseSelectCell = Please select a cell first
SelectComport = Please select a comport
WarningLogBrowseFMTMissing = Log Browse will not function correctly without FMT messages in your log.
    These appear to be missing from your log.
WarningUpdateParamList = Update Params
    DON'T DO THIS IF YOU ARE IN THE AIR
    {""}
Checking = Checking{" "}
DownloadedFromInternet = Downloaded from internet
Getting = Getting{" "}
GettingUpdatedParams = Getting updated parameters
AdvancedParams = Advanced Params
BasicTuning = Basic Tuning
Desc = Description:{" "}
ExtendedTuning = Extended Tuning
FlightModes = Flight Modes
FullParameterList = Full Parameter List
FullParameterTree = Full Parameter Tree
GeoFence = GeoFence
StandardParams = Standard Params
Units = Units: { $arg0 }{ $arg1 }
ProgrammedOK = Sucessfully programmed
CONNECTc = CONNECT
Disconnect = Disconnect
DISCONNECTc = DISCONNECT
Failclog = Failed to create ground station log - wont log this session
NewFirmware = New Firmware
NewFirmwareA = New firmware available
    {""}
Pleaseup = {""}
    Please upgrade
Stillmoving = Your model is still moving are you sure you want to disconnect?
Timeout = Timeout waiting for autoscan/no mavlink device connected
ConnectFailed = Connect Failed
ConnectingMavlink = Connecting Mavlink
Done = Done
GettingParams = Getting Params
GettingParamsD = Getting Params...
Gotparam = Got param{" "}
MavlinkConnecting = Mavlink Connecting...
Only1Hb = Only 1 Heatbeat Received
Only1HbD = Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
    Mission Planner waits for 2 valid heartbeat packets before connecting
Trying = Trying to connect.
    Timeout in { $arg0 }
CantDetectBoardVersion = Cant detect your Board version. Please check your cabling
CheckPortSettingsOr = Check port settings or Port in use?
CommunicationErrorNoConnection = Communication Error - no connection
DetectedA = Detected a{" "}
DetectingBoardVersion = Detecting Board Version
DownloadingFromInternet = Downloading from Internet
EppromChanged = Epprom changed, all your setting will be lost during the update,
    Do you wish to continue?
EppromFormatChanged = Epprom format changed ({"{"}0) vs { $arg1 })
FailedDownload = Failed download
FailedReadHEX = Failed read HEX
FailedToReadHex = Failed to read firmware.hex :
FailedUpload = Failed upload
GettingFWList = Getting FW List
GettingFWVersion = Getting FW Version
InvalidBoardType = Invalid Board Type
PleaseConnectAndBackupConfig = Please connect and backup your config in the configuration tab.
ReadingHexFile = Reading Hex File
ReceivedList = Received List
UploadComplete = Upload Complete
UploadingBytesToBoard = Uploading { $arg0 } bytes to Board:
VerifyComplete = Verify Complete
VerifyFirmware = Verify Firmware
UploadSucceededButVerifyFailed = Upload succeeded, but verify failed: exp { $arg0 } got { $arg1 } at{" "}
ReadingHex = Reading Hex
Warningrallypointdistance = Warning rally points are located greater than RALLY_LIMIT_KM
Warning = Warning
WarningAC32 = Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration.
WarningAC31 = Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter
MagCalibMsg = Please click ok and move the autopilot around all axises in a circular motion
MissingDataPoints = You are missing data points. do you want to run the calibration anyway?
RunAnyway = run anyway
UpdateFound = Update Found
    {""}
    Do you wish to update now?{" "}
UpdateNow = Update Now
RawParamWarning = Raw Param Warning
RawParamWarningi = All values on this screen are not min/max checked. Please double check your input.
    Please use Standard/Advanced Params for the safe settings
ShowMeAgain = Show me again?
OK = OK
LinkStats = Link Stats
Stop = Stop
Connect = Connect
Start = Start
AreYouSureYouWantToUpload = Are you sure you want to upload{" "}
Beta = Beta
BetaWarning = These are beta firmware, use at your own risk!!!
CanNotConnectToComPortAnd = Can not connect to com port and detect board type
Continue = Continue
ErrorUploadingFirmware = Error uploading firmware
QuestionMark = ?
Trunk = trunk
TrunkWarning = These are the latest trunk firmware, use at your own risk!!!
BadGPSHealth = Unhealthy GPS Signal
BadAirspeed = Unhealthy Airspeed
BadGyroHealth = Bad Gyro Health
BadAccelHealth = Bad Accel Health
BadCompassHealth = Bad Compass Health
BadBaroHealth = Bad Baro Health
BadLiDARHealth = Bad LiDAR Health
BadOptFlowHealth = Bad OptFlow Health
BadorNoTerrainData = Bad or No Terrain Data
GeofenceBreach = Geofence Breach
BadAHRS = Unhealthy AHRS
NORCReceiver = NO RC Receiver
AutoWP = Auto WP
EnsurePropsNotOn = Ensure your props are not on the Plane/Quad
FailSafe = FailSafe
Error_binding = Error binding
Put_the_transmitter_in_bind_mode__Receiver_is_waiting = Put the transmitter in bind mode. Receiver is waiting.
Completed = Completed
Click_when_Done = Click when Done
Saving = Saving
InvalidCert = Invalid Cert
Note = Note
PleaseUnplugTheBoardAnd = Please unplug the board, and then press OK and plug back in.
    Mission Planner will look for 30 seconds to find the board
ThisBoardHasBeenRetired = This board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0)
YouAreUsingUnsupportedHardware = You are using unsupported hardware.
    This board does not contain a valid certificate of authenticity.
    Please contact your hardware vendor about signing your hardware.
NoNeedToUpload = No need to upload. already on the board
PleaseWaitForTheMusicalTones = Please wait for the musical tones to finish before clicking OK
ObtainFromModule = Obtain From Module
SetHere = Set Here
TrackerHome = Tracker Home
velocity_variance = velocity variance
compass_variance = compass variance
pos_horiz_variance = pos horiz variance
pos_vert_variance = pos vert variance
terrain_alt_variance = terrain alt variance
ChangeThrottle = Change Throttle
Invalid_home_location = Invalid home location
Converting_bin_to_log = Converting bin to log
UpdateNotFound = No update available.
Failed_to_connect_to_SITL_instance = Failed to connect to SITL instance
Scanning_File = Scanning File
Zoom_to_the_center_or_the_loaded_file = Zoom to the center or the loaded file?
Zoom_To = Zoom To
Do_you_want_to_load_this_into_the_flight_data_screen = Do you want to load this into the flight data screen?
Load_data = Load data
Bad_KML_File = Bad KML File :
No_valid_heartbeats_read_from_port = No valid heartbeats read from port
Bad_Vision_Position = Bad Vision Position
BadLogging = Bad Logging
ParamRefreshRequired = A Param refresh is required - Please press F5
    old #{ $arg0 }  new #{ $arg1 }
Failed_to_download_the_SITL_image = Failed to download the SITL image.
Not_available_when_used_as_a_windows_store_app = Not available when used as a windows store app
No_firmware_available_for_this_board = No firmware available for this board!
OnboardOSD = Onboard OSD
User_Params = User Params
Planner = Planner
Cancel = Cancel
No_valid_sik_radio = No valid sik radio
MAVFtp = MAVFtp
Bad_Battery = Bad Battery
Bad_Proximity = Bad Proximity
Bad_SatCom = Bad SatCom
Prearm_check_failed = Prearm check failed - check messages
Invalid_Location = Invalid Location
Loading = Loading
ZeroAltWarningCopter = WP# { $arg0 } has zero altitude, this means no altitude change! If you want zero altitude, change it to 0.01. Do you want to continue or cancel wp upload?
ZeroAltWarningTitle = Zero Altitude Warning
ZeroAltWarningPlane = WP# { $arg0 } has zero altitude. If you actually want zero altitude, change it to 0.01 instead for predictable behavior.
    {""}
    On ArduPlane, zero altitudes may interpreted in two different ways: actual zero altitude, or keep current altitude. WAYPOINT commands will generally honor a zero altitude and LOITER commands will generally interpret it as "use current altitude", but only if the altitude frame is "relative". There may be more exceptions and this could change in future versions.
    {""}
    ONLY SET TO ZERO IF YOU REALLY UNDERSTAND EXACTLY WHAT IS GOING TO HAPPEN IN YOUR CASE (use a simulator to be sure).[link;https://ardupilot.org/plane/docs/common-mavlink-mission-command-messages-mav_cmd.html;Command Documentation]
