//! The clock-driven `CurrentState` fields held to Mission Planner's own code.
//!
//! `testdata/currentstate` is what `ExtLibs/ArduPilot/CurrentState.cs` itself computed, run under
//! mono by `tools/csharp-reference/MpState.cs` (regenerated by `regen-state.sh`):
//!
//! * `<log>.csv`: every recorded flight in `testdata/mavlink`, and `synthetic.tlog` - a flight
//!   the harness writes to reach what the recorded ones do not - played through
//!   `MAVLinkInterface` in log-read mode, with `UpdateCurrentSettings` on every vehicle after each
//!   packet, and the fields of vehicle 1:1 written whenever one changed. Here the same log goes
//!   through [`VehicleRegistry::apply_at`], stamped with each record's time as
//!   `readlogPacketMavlink` reads it, and [`VehicleRegistry::update_current_settings`] - the path
//!   a replay takes - and every field must equal the C#'s after every packet, to the bit.
//! * `getters.csv`: the derived getters on a grid of inputs, including the divisions by zero.
//! * `fence.csv`: `GeoFenceDist` for a set of fences and positions around them.
//!
//! The statics these read - the tracker location, the planned home, the K-index, the rate
//! defaults, the custom field names - are process-wide, so every test here takes [`LOCK`].

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::float_cmp,
    clippy::indexing_slicing,
    clippy::cast_possible_truncation
)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::{Mutex, MutexGuard, PoisonError};

use mp_mavlink::FrameDecoder;
use mp_mavlink_dialects::all::{DIALECT, MavMessage};
use mp_units::{LatLon, Metres};
use mp_vehicle::{DateTime, FenceItem, LatLngAlt, VehicleId, VehicleRegistry, VehicleState};

/// Serialises the tests that read or write the process-wide statics.
static LOCK: Mutex<()> = Mutex::new(());

fn lock() -> MutexGuard<'static, ()> {
    LOCK.lock().unwrap_or_else(PoisonError::into_inner)
}

fn testdata(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata")
        .join(path)
}

/// A double as the harness wrote it with `"R"`: digits, `NaN`, `Infinity` or `-Infinity`.
fn number(text: &str) -> f64 {
    match text {
        "NaN" => f64::NAN,
        "Infinity" => f64::INFINITY,
        "-Infinity" => f64::NEG_INFINITY,
        _ => text
            .parse()
            .unwrap_or_else(|_| panic!("not a number: {text}")),
    }
}

/// The same value, bit for bit, or both NaN - except the sign of a zero, which mono's `"R"`
/// does not write: -0 prints as `0`.
fn same(ours: f64, theirs: f64) -> bool {
    (ours.is_nan() && theirs.is_nan()) || ours.to_bits() == theirs.to_bits() || ours == theirs
}

/// Each packet of a `.tlog` as `readlogPacketMavlink` reads it: an 8-byte big-endian stamp -
/// unless the first of those bytes is a start byte, when it reads none - then a frame from the
/// next start byte, skipping whatever is not one, as long as its header says. What it reads need
/// not be a frame: past bytes that are not MAVLink it can start inside a stamp, and then the
/// packet is garbage that fails its checksum, and still counts.
/// `// C#: ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs:6510-6647`
fn records(data: &[u8]) -> Vec<Record<'_>> {
    let is_stx = |byte: u8| matches!(byte, 0xFE | 0xFD);
    let mut out = Vec::new();
    let mut pos = 0;
    while pos < data.len() {
        // C#: MAVLinkInterface.cs:6535-6563
        let mut stamp = None;
        if is_stx(data[pos]) {
            // "rewind 8bytes"
        } else {
            let mut bytes = [0_u8; 8];
            let available = data.len().min(pos + 8) - pos;
            bytes[..available].copy_from_slice(&data[pos..pos + available]);
            stamp = Some(u64::from_be_bytes(bytes));
            pos += available;
        }
        // C#: MAVLinkInterface.cs:6576-6604, the start byte, scanning past anything else.
        let Some(start) = data[pos..].iter().position(|&byte| is_stx(byte)) else {
            out.push(Record {
                stamp,
                frame: &data[pos..pos],
                end: data.len(),
            });
            break;
        };
        let start = pos + start;
        // C#: MAVLinkInterface.cs:6608-6640
        let v2 = data[start] == 0xFD;
        let length = data.get(start + 1).map_or(1, |&len| {
            let signed = v2 && data.get(start + 2).is_some_and(|flags| flags & 1 != 0);
            usize::from(len) + if v2 { 10 } else { 6 } + 2 + if signed { 13 } else { 0 }
        });
        let end = data.len().min(start + length);
        out.push(Record {
            stamp,
            frame: &data[start..end],
            end,
        });
        pos = end;
    }
    out
}

/// One packet's worth of a `.tlog`, as [`records`] splits it.
struct Record<'a> {
    /// The stamp read before it, if one was.
    stamp: Option<u64>,
    /// What was read as the frame.
    frame: &'a [u8],
    /// The file position after it.
    end: usize,
}

/// One row of the C#'s output: the file position after its packet, and each column's text.
struct Row {
    position: usize,
    columns: BTreeMap<String, String>,
}

/// What the C# wrote for one log.
struct Oracle {
    rows: Vec<Row>,
    /// From its `# packets` line.
    packets: usize,
    /// From its `# customfield<n>=<name>` lines, in the order the dictionary holds them.
    names: Vec<(usize, String)>,
}

/// Reads `<log>.csv`.
fn oracle(name: &str) -> Oracle {
    let text = std::fs::read_to_string(testdata(&format!("currentstate/{name}.csv"))).unwrap();
    let mut lines = text.lines();
    let header: Vec<&str> = lines.next().unwrap().split(',').collect();
    let mut rows = Vec::new();
    let mut packets = 0;
    let mut names = Vec::new();
    for line in lines {
        if let Some(count) = line.strip_prefix("# packets ") {
            packets = count.parse().unwrap();
            continue;
        }
        if let Some(named) = line.strip_prefix("# customfield") {
            let (index, name) = named.split_once('=').unwrap();
            names.push((index.parse().unwrap(), name.to_owned()));
            continue;
        }
        let values: Vec<&str> = line.split(',').collect();
        assert_eq!(values.len(), header.len(), "{line}");
        rows.push(Row {
            position: values[1].parse().unwrap(),
            columns: header
                .iter()
                .zip(&values)
                .map(|(key, value)| ((*key).to_owned(), (*value).to_owned()))
                .collect(),
        });
    }
    Oracle {
        rows,
        packets,
        names,
    }
}

/// Vehicle 1:1's fields, as the harness writes them, from this port.
fn ours(state: &VehicleState) -> Vec<(&'static str, f64)> {
    let tracker = state.tracker_location();
    let planned = VehicleState::planned_home();
    let mut fields = vec![
        ("alt", f64::from(state.alt())),
        ("altoffsethome", f64::from(state.alt_offset_home)),
        ("verticalspeed", f64::from(state.vertical_speed())),
        ("climbrate", state.climb_rate.0),
        ("distTraveled", f64::from(state.dist_traveled)),
        ("timeSinceArmInAir", f64::from(state.time_since_arm_in_air)),
        ("timeInAir", f64::from(state.time_in_air)),
        ("timeInAirMinSec", f64::from(state.time_in_air_min_sec())),
        ("battery_usedmah", state.battery_used_mah),
        ("battery_mahperkm", state.battery_mah_per_km()),
        ("battery_kmleft", state.battery_km_left()),
        (
            "DistFromMovingBase",
            f64::from(state.dist_from_moving_base()),
        ),
        ("tracker_lat", tracker.lat),
        ("tracker_lng", tracker.lng),
        ("tracker_alt", tracker.alt),
        ("GeoFenceDist", f64::from(state.geo_fence_dist(&[]))),
        ("lowairspeed", f64::from(u8::from(state.low_airspeed))),
        ("rateattitude", f64::from(state.rates.attitude)),
        ("rateposition", f64::from(state.rates.position)),
        ("ratestatus", f64::from(state.rates.status)),
        ("ratesensors", f64::from(state.rates.sensors)),
        ("raterc", f64::from(state.rates.rc)),
        ("KIndex", f64::from(VehicleState::kindex())),
        ("gimballat", f64::from(state.gimbal_lat())),
        ("gimballng", f64::from(state.gimbal_lng())),
        ("timesincelastshot", state.time_since_last_shot),
        ("planned_lat", planned.lat),
        ("planned_lng", planned.lng),
        ("planned_alt", planned.alt),
    ];
    const HIL: [&str; 8] = [
        "hilch1", "hilch2", "hilch3", "hilch4", "hilch5", "hilch6", "hilch7", "hilch8",
    ];
    for (name, value) in HIL.iter().zip(state.hil_channels) {
        fields.push((name, f64::from(value)));
    }
    const CUSTOM: [&str; 20] = [
        "customfield0",
        "customfield1",
        "customfield2",
        "customfield3",
        "customfield4",
        "customfield5",
        "customfield6",
        "customfield7",
        "customfield8",
        "customfield9",
        "customfield10",
        "customfield11",
        "customfield12",
        "customfield13",
        "customfield14",
        "customfield15",
        "customfield16",
        "customfield17",
        "customfield18",
        "customfield19",
    ];
    for (name, value) in CUSTOM.iter().zip(state.custom_fields) {
        fields.push((name, f64::from(value)));
    }
    fields
}

/// The two parameters the low-airspeed warning reads, as a parameter table would hand them to
/// [`VehicleState::set_airspeed_min_params`]: `MAVLinkInterface` files every `PARAM_VALUE` in
/// the sender's `MAV.param` as it passes, log playback included (`MAVLinkInterface.cs:5766-5796`),
/// and the C#'s `VFR_HUD` reads them from there.
#[derive(Default)]
struct AirspeedParams {
    airspeed_min: Option<f64>,
    arspd_fbw_min: Option<f64>,
}

impl AirspeedParams {
    /// Takes a `PARAM_VALUE`; true when it was one of the two.
    fn take(&mut self, message: &MavMessage) -> bool {
        let MavMessage::ParamValue(value) = message else {
            return false;
        };
        let id = value.param_id.split(|&byte| byte == 0).next().unwrap();
        let slot = match id {
            b"AIRSPEED_MIN" => &mut self.airspeed_min,
            b"ARSPD_FBW_MIN" => &mut self.arspd_fbw_min,
            _ => return false,
        };
        *slot = Some(f64::from(value.param_value));
        true
    }
}

/// Plays `<path>.tlog` as the C#'s log playback does and holds vehicle 1:1 to the C#'s fields in
/// `testdata/currentstate/<name>.csv` after every packet. Returns what the C# wrote.
fn replay_against_the_csharp(name: &str, path: &str) -> Oracle {
    // The custom fields' names are process-wide; each flight names them as its own log does.
    VehicleState::clear_custom_field_names();
    let data = std::fs::read(testdata(path)).unwrap();
    let oracle = oracle(name);
    let (rows, packets) = (&oracle.rows, oracle.packets);
    let mut records = records(&data).into_iter();

    let autopilot = VehicleId::new(1, 1);
    let mut registry = VehicleRegistry::new();
    let mut params = AirspeedParams::default();
    // C#: MAVLinkInterface.cs:483, `lastlogread` starts at MinValue and keeps its last value
    // through a record without a usable stamp.
    let mut last_log_read = DateTime::MIN;
    let mut next = rows.iter().peekable();
    let mut current: Option<&Row> = None;
    let mut compared = 0;
    let mut packet = 0;
    let mut garbage = 0;
    let mut position = 0;
    'packets: while let Some(first) = records.next() {
        packet += 1;
        let mut record = first;
        // One readPacketAsync: a record, and after one that fails its checksum with a start
        // byte in its last twenty bytes, the next, in the same call.
        // C#: MAVLinkInterface.cs:4697-4716, 4995-5021
        loop {
            position = record.end;
            if let Some(time) = record.stamp.and_then(DateTime::from_tlog_micros) {
                last_log_read = time;
            }
            // The packet is the frame the C# read, or nothing: a decoder that resynchronised
            // to a frame inside garbage would find one the C# does not.
            let frame = record.frame;
            let mut decoded_it = false;
            let mut decoder = FrameDecoder::new();
            decoder.push_and_drain(frame, &DIALECT, |decoded| {
                if decoded.raw != frame {
                    return;
                }
                decoded_it = true;
                if let Some(message) = MavMessage::decode(decoded.msgid, decoded.payload) {
                    let id = registry.apply_at(
                        decoded.sysid,
                        decoded.compid,
                        decoded.seq,
                        &message,
                        last_log_read,
                    );
                    if params.take(&message)
                        && let Some(state) = registry.working_mut(id)
                    {
                        state.set_airspeed_min_params(params.airspeed_min, params.arspd_fbw_min);
                    }
                }
            });
            if decoded_it {
                break;
            }
            garbage += 1;
            let tail = frame.len().saturating_sub(20).max(1);
            if !frame.get(tail..).is_some_and(|tail| tail.contains(&0xFD)) {
                break;
            }
            let Some(following) = records.next() else {
                break 'packets;
            };
            record = following;
        }
        // C#: Log/MavlinkLog.cs:141-144
        registry.update_current_settings(false);

        // The C#'s rows up to here, by where in the file each was written: where the bytes are
        // not MAVLink the two need not agree on how many reads that took.
        let mut fresh = None;
        while let Some(row) = next.next_if(|row| row.position <= position) {
            fresh = Some(row);
        }
        let fresh = fresh.filter(|row| row.position == position);
        if fresh.is_some() {
            current = fresh;
        }
        let Some(row) = current else {
            assert!(
                registry.working(autopilot).is_none(),
                "packet {packet}: the C# had no vehicle 1:1 yet"
            );
            continue;
        };
        let state = registry.working(autopilot).expect("vehicle 1:1");
        if fresh.is_some() {
            // The clock is written only with a row; between rows it moved on unrecorded.
            assert_eq!(
                state.datetime.ticks().to_string(),
                row.columns["datetime_ticks"],
                "packet {packet}: datetime"
            );
        }
        for (field, value) in ours(state) {
            let theirs = number(&row.columns[field]);
            assert!(
                same(value, theirs),
                "{name} packet {packet}: {field} is {value:?}, the C#'s {theirs:?}"
            );
        }
        compared += 1;
    }
    assert_eq!(position, data.len());
    if garbage == 0 {
        assert_eq!(packet, packets, "the C# read {packets} packets");
    }
    assert!(next.peek().is_none(), "rows left over");
    assert!(compared > 3_000, "compared {compared} packets");
    eprintln!("{name}: {packet} packets, {garbage} records that are not frames");
    // The custom fields' names, which are process-wide: this log's are the only ones here.
    for index in 0..20 {
        let theirs = oracle
            .names
            .iter()
            .find(|(field, _)| *field == index)
            .map(|(_, name)| name.clone());
        assert_eq!(
            VehicleState::custom_field_name(index),
            theirs,
            "customfield{index}"
        );
    }
    oracle
}

#[test]
fn the_autotest_flight_matches_the_csharp_packet_by_packet() {
    let _guard = lock();
    let oracle = replay_against_the_csharp("autotest", "mavlink/autotest.tlog");
    // The flight arms and climbs: fifteen seconds in the air, a vertical speed and a used
    // capacity that change thousands of times.
    assert!(oracle.rows.len() > 3000, "{} rows", oracle.rows.len());
}

#[test]
fn the_multisystem_flight_matches_the_csharp_packet_by_packet() {
    let _guard = lock();
    let oracle = replay_against_the_csharp("multisystem", "mavlink/multisystem.tlog");
    assert!(oracle.rows.len() > 400, "{} rows", oracle.rows.len());
}

/// The distinct values the C# wrote in one column.
fn distinct(oracle: &Oracle, column: &str) -> usize {
    oracle
        .rows
        .iter()
        .map(|row| row.columns[column].as_str())
        .collect::<std::collections::BTreeSet<_>>()
        .len()
}

#[test]
fn the_synthetic_flight_matches_the_csharp_packet_by_packet() {
    // `MpState.cs mktlog`'s flight: arming twice, a track flown on a 3D fix and without one,
    // the current sensor absent and then present, the clock back 3 s and on 61 s, VFR_HUD only
    // after 20 s, the airspeed low and its sensor unhealthy, twenty-four names for twenty custom
    // fields, and HIL controls with a NaN and an overflow.
    let _guard = lock();
    let oracle = replay_against_the_csharp("synthetic", "currentstate/synthetic.tlog");
    // What the recorded flights never move, this one does.
    for (column, at_least) in [
        ("distTraveled", 50),
        ("timeSinceArmInAir", 50),
        ("timeInAir", 90),
        ("battery_usedmah", 100),
        ("lowairspeed", 2),
        ("hilch1", 100),
        ("hilch4", 3),
        ("customfield0", 100),
        ("customfield19", 2),
        ("climbrate", 5),
        ("verticalspeed", 50),
    ] {
        let seen = distinct(&oracle, column);
        assert!(seen >= at_least, "{column}: {seen} values");
    }
    assert_eq!(oracle.names.len(), 20, "every field named");
    assert_eq!(oracle.names[0], (0, "MAV_ALPHA".to_owned()));
    assert_eq!(oracle.names[1], (1, "MAV_BETA".to_owned()), "upper-cased");
}

/// Reads `getters.csv`'s rows of one kind, header first.
fn getters(kind: &str) -> Vec<Vec<String>> {
    let text = std::fs::read_to_string(testdata("currentstate/getters.csv")).unwrap();
    text.lines()
        .map(|line| line.split(',').map(str::to_owned).collect::<Vec<_>>())
        .filter(|fields| fields[0] == kind)
        .skip(1)
        .collect()
}

#[test]
fn time_in_air_min_sec_matches_the_csharp() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:1195-1197
    let rows = getters("minsec");
    assert_eq!(rows.len(), 12);
    for row in rows {
        let mut state = VehicleState::default();
        state.time_in_air = number(&row[1]) as f32;
        let theirs = number(&row[2]);
        assert!(
            same(f64::from(state.time_in_air_min_sec()), theirs),
            "timeInAir {}: {} against {theirs}",
            row[1],
            state.time_in_air_min_sec()
        );
    }
}

#[test]
fn the_battery_estimates_match_the_csharp_including_the_divisions_by_zero() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:1471-1480
    let rows = getters("battery");
    assert_eq!(rows.len(), 36);
    for row in rows {
        let mut state = VehicleState::default();
        state.battery_used_mah = number(&row[1]);
        state.dist_traveled = number(&row[2]) as f32;
        state.battery.remaining_percent = row[3].parse().unwrap();
        let (per_km, left) = (number(&row[4]), number(&row[5]));
        assert!(
            same(state.battery_mah_per_km(), per_km),
            "{row:?}: mah/km {}",
            state.battery_mah_per_km()
        );
        assert!(
            same(state.battery_km_left(), left),
            "{row:?}: km left {}",
            state.battery_km_left()
        );
    }
}

#[test]
fn the_distance_from_the_moving_base_matches_the_csharp() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:1786-1805
    let rows = getters("base");
    assert_eq!(rows.len(), 12);
    for row in rows {
        let (lat, lng) = (number(&row[3]), number(&row[4]));
        let mut state = VehicleState::default();
        state.base = LatLngAlt {
            lat: number(&row[1]),
            lng: number(&row[2]),
            alt: 12.5,
        };
        // The C#'s (0, 0) is no position here.
        state.position = (lat != 0.0 || lng != 0.0).then(|| LatLon::new(lat, lng).unwrap());
        let theirs = number(&row[5]);
        assert!(
            same(f64::from(state.dist_from_moving_base()), theirs),
            "{row:?}: {}",
            state.dist_from_moving_base()
        );
    }
}

#[test]
fn the_tracker_location_falls_back_to_home_as_the_csharps_does() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:1606-1615
    let _guard = lock();
    let rows = getters("tracker");
    assert_eq!(rows.len(), 4);
    for row in rows {
        VehicleState::set_tracker_location(LatLngAlt {
            lat: number(&row[1]),
            lng: number(&row[2]),
            alt: number(&row[3]),
        });
        let mut state = VehicleState::default();
        state.home = Some(LatLon::new(number(&row[4]), number(&row[5])).unwrap());
        state.home_altitude = Metres(number(&row[6]));
        let got = state.tracker_location();
        assert!(
            same(got.lat, number(&row[7]))
                && same(got.lng, number(&row[8]))
                && same(got.alt, number(&row[9])),
            "{row:?}: {got:?}"
        );
    }
    VehicleState::set_tracker_location(LatLngAlt::ZERO);
}

#[test]
fn the_gimbal_point_reads_as_the_csharps_floats() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:2024-2042
    let rows = getters("gimbal");
    assert_eq!(rows.len(), 2);
    let unset = VehicleState::default();
    assert!(same(f64::from(unset.gimbal_lat()), number(&rows[0][3])));
    assert!(same(f64::from(unset.gimbal_lng()), number(&rows[0][4])));
    let mut set = VehicleState::default();
    set.gimbal_point = Some(LatLngAlt {
        lat: number(&rows[1][1]),
        lng: number(&rows[1][2]),
        alt: 10.0,
    });
    assert!(same(f64::from(set.gimbal_lat()), number(&rows[1][3])));
    assert!(same(f64::from(set.gimbal_lng()), number(&rows[1][4])));
}

/// The fences `MpState.cs fence` put in `MAVState.fencepoints`, as `(command, param1, lat, lng)`.
fn fences() -> BTreeMap<&'static str, Vec<(u16, f32, f64, f64)>> {
    BTreeMap::from([
        ("empty", vec![]),
        (
            "inclusion",
            vec![
                (5001, 4.0, -35.362, 149.164),
                (5001, 4.0, -35.362, 149.1665),
                (5001, 4.0, -35.364, 149.1665),
                (5001, 4.0, -35.364, 149.164),
            ],
        ),
        (
            "exclusion",
            vec![
                (5002, 3.0, -35.3625, 149.1650),
                (5002, 3.0, -35.3625, 149.1660),
                (5002, 3.0, -35.3635, 149.1655),
            ],
        ),
        (
            "circles",
            vec![
                (5000, 0.0, -35.3630, 149.1650),
                (5003, 300.0, -35.3630, 149.1650),
                (5004, 25.0, -35.3632, 149.1652),
            ],
        ),
        (
            "mixed",
            vec![
                (5001, 3.0, -35.360, 149.160),
                (5001, 3.0, -35.360, 149.170),
                (5001, 3.0, -35.368, 149.165),
                (5001, 3.0, -35.361, 149.162),
                (5001, 3.0, -35.361, 149.168),
                (5001, 3.0, -35.366, 149.165),
                (5004, 40.0, -35.3635, 149.1655),
            ],
        ),
        (
            "short",
            vec![
                (5001, 3.0, -35.362, 149.164),
                (5001, 3.0, -35.362, 149.1665),
                (5001, 3.0, -35.364, 149.1665),
                (5001, 3.0, -35.364, 149.164),
            ],
        ),
    ])
}

#[test]
fn the_geofence_distance_matches_the_csharp() {
    // C#: ExtLibs/ArduPilot/CurrentState.cs:1617-1753
    let fences = fences();
    let text = std::fs::read_to_string(testdata("currentstate/fence.csv")).unwrap();
    let mut checked = 0;
    let mut kinds = std::collections::BTreeSet::new();
    for line in text.lines().skip(1) {
        let row: Vec<&str> = line.split(',').collect();
        let fence: Vec<FenceItem> = fences[row[0]]
            .iter()
            .map(|&(command, param1, lat, lng)| FenceItem {
                command,
                param1,
                // `(int)Math.Round(item * 1e7)`, as the harness rounds them: to even.
                x: (lat * 1e7).round_ties_even() as i32,
                y: (lng * 1e7).round_ties_even() as i32,
            })
            .collect();
        let (lat, lng) = (number(row[1]), number(row[2]));
        let mut state = VehicleState::default();
        state.position = (lat != 0.0 || lng != 0.0).then(|| LatLon::new(lat, lng).unwrap());
        let ours = state.geo_fence_dist(&fence);
        let theirs = number(row[3]);
        assert!(
            same(f64::from(ours), theirs),
            "{line}: {ours} against the C#'s {theirs}"
        );
        // Each kind of answer is reached: none, breached, and a distance.
        kinds.insert(match theirs {
            99999.0 => "no fence",
            0.0 => "breached",
            _ => "distance",
        });
        checked += 1;
    }
    assert_eq!(checked, 6 * 51);
    assert_eq!(kinds.len(), 3, "{kinds:?}");
}
