# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.zh-Hant.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 30 of 135 keys.

flightdata-BUTactiondo-Text = 執行
flightdata-BUTrestartmission-Text = 重重開始任務
flightdata-BUT_ARM-Text = 解鎖/ 上鎖
flightdata-BUT_clear_track-Text = 清除軌跡
flightdata-BUT_joystick-Text = 遙桿
flightdata-BUT_loadtelem-Text = 載入 Log
flightdata-BUT_loganalysis-Text = Log 分析
flightdata-BUT_playlog-Text = 播放/暫停
flightdata-BUT_quickauto-Text = 自動
flightdata-BUT_quickrtl-Text = 返航
flightdata-BUT_run_script-Text = 執行腳本
flightdata-BUT_select_script-Text = 選擇腳本
flightdata-CMB_setwp-Items = 家高度=0
flightdata-deleteToolStripMenuItem-Text = 刪除
flightdata-flightPlannerToolStripMenuItem-Text = 飛行計畫
flightdata-goHereToolStripMenuItem-Text = 飛到航點
flightdata-label2-Text = 速度
flightdata-myButton2-Text = 返航
flightdata-myButton3-Text = 自動
flightdata-saveFileToolStripMenuItem-Text = 儲存檔案
flightdata-stopRecordToolStripMenuItem-Text = 停止記錄
flightdata-tabActions-Text = 執行
flightdata-tabActionsSimple-Text = 執行
flightdata-tablogbrowse-Text = 飛行記錄
flightdata-tabPagemessages-Text = 訊息
flightdata-tabQuick-Text = 儀錶板
flightdata-tabScripts-Text = 腳本
flightdata-tabServo-Text = 舵機
flightdata-tabStatus-Text = 狀態
flightdata-tabTLogs-Text = 數傳記錄
