// Copyright (C) 2026 David "Buzz" Bussenschutt
//
// This file is part of MissionPlannerRust, a Rust implementation derived from
// Mission Planner (Copyright (C) 2010-2024 Michael Oborne and contributors,
// https://github.com/ArduPilot/MissionPlanner); NOTICE records the changes.
//
// MissionPlannerRust is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by the
// Free Software Foundation, version 3 of the License.
//
// MissionPlannerRust is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU General Public License along with
// MissionPlannerRust. If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-only

//! The WebAssembly plugin host: Mission Planner's plugins, loaded from `plugins/` beside the
//! executable and run on wasmtime's component model.
//!
//! PLAN.md §13.6 row 96, on row 95's experiment (removed 2026-10-05, this crate its successor). The C# loads
//! every `.dll` in its plugins folder and compiles every `.cs` there at run time
//! (`Plugin/PluginLoader.cs`); each plugin derives `MissionPlanner.Plugin.Plugin` and reaches the
//! application through a `PluginHost` (`Plugin/Plugin.cs`). Neither a .NET assembly nor run-time
//! C# can exist here; a plugin is a WebAssembly component of the world in `wit/plugin.wit`:
//!
//! * the `Plugin` lifecycle is the world's exports - `name`, `version`, `author`,
//!   `loop-rate-hz`, `init`, `loaded`, `loop`, `exit` - with a menu entry's click and a form's
//!   event, which the C# delivers as .NET events;
//! * `PluginHost` is the `host` interface the plugin imports, and [`Surface`] is the Rust side of
//!   it: the application implements it (through [`ChannelSurface`], which carries every call to
//!   the window's thread as a [`Request`]), a test implements it with a script.
//!
//! [`Plugin`] is one plugin loaded and driven synchronously; [`PluginHost`] is
//! `PluginLoader.LoadAll` and `MainV2.PluginThread`: every `*.wasm` in a folder, each on a thread
//! of its own at its `loopratehz`, with fuel.
//!
//! What the C# cannot do and this does: a plugin that panics or traps is a status line and is
//! unloaded, where the C#'s exception takes down its thread or the application; a plugin that
//! never returns is stopped by its fuel, where the C#'s plugin thread hangs; a plugin reaches only
//! what the world imports - no file, socket or clock the host did not hand it.

mod channel;
mod plugin;
mod runner;
// A web page's half of the plugin host: wasmtime's platform functions and loading Pulley bytecode.
#[cfg(target_family = "wasm")]
mod web;

pub use channel::{
    ANSWER_WAIT, ChannelSurface, CsReader, DEMO_ANSWER_WAIT, OptionsReader, Reply, Request,
    RequestBody, Snapshot, TerrainReader,
};
pub use plugin::{Fault, Info, Limits, Plugin, engine, web_config};
#[cfg(not(target_family = "wasm"))]
pub use plugin::precompile_for_web;
pub use runner::{INIT_REFUSED, PluginHost, PluginSource, PluginState, PluginStatus, plugins_dir};

/// The WIT world's bindings, generated by wasmtime from `wit/plugin.wit`.
#[allow(missing_docs, unreachable_pub, clippy::all)]
mod wit {
    wasmtime::component::bindgen!({
        path: "wit",
        world: "plugin",
        additional_derives: [PartialEq],
    });
}

pub use wit::missionplanner::plugin::host::{
    Area, Control, ControlKind, CsValue, DialogResult, FencePoint, MapMenu, MessageButtons,
    OpenedFile, Waypoint,
};

/// `PluginHost`: everything a plugin may reach of the application, one method per import of the
/// world's `host` interface (`wit/plugin.wit` says what each one is in the C#).
///
/// Called on the plugin's own thread, while the plugin waits: a method that needs the user (a
/// message box, an input box, a file dialog) blocks until the answer comes.
pub trait Surface: Send + 'static {
    /// `Host.cs.<name>`.
    fn cs(&mut self, name: &str) -> Option<CsValue>;
    /// `Host.comPort.MAV.param[name]`.
    fn get_param(&mut self, name: &str) -> Option<f64>;
    /// `ParameterMetaDataRepository.GetParameterOptionsInt`.
    fn param_options(&mut self, name: &str) -> Vec<(i32, String)>;
    /// `Host.comPort.setParam`.
    fn set_param(&mut self, name: &str, value: f64) -> bool;
    /// `Host.comPort.setMode`.
    fn set_mode(&mut self, mode: &str) -> bool;
    /// `Host.comPort.sendPacket`.
    fn send_packet(&mut self, message_id: u32, payload: Vec<u8>) -> bool;
    /// `Host.FDMenuMap.Items.Add` / `Host.FPMenuMap.Items.Add`: the new entry's id.
    fn menu_add(&mut self, menu: MapMenu, parent: Option<u32>, text: &str) -> u32;
    /// `CustomMessageBox.Show`.
    fn message_box(&mut self, text: &str, caption: &str, buttons: MessageButtons) -> DialogResult;
    /// `InputBox.Show`.
    fn input_box(&mut self, title: &str, prompt: &str, value: &str) -> Option<String>;
    /// The status line.
    fn status(&mut self, text: &str);
    /// `log.Info`.
    fn log(&mut self, text: &str);
    /// `Host.AddWPtoList`.
    fn add_wp(&mut self, wp: Waypoint) -> i32;
    /// `Host.InsertWP`.
    fn insert_wp(&mut self, index: i32, wp: Waypoint);
    /// `Host.GetWPs`.
    fn get_wps(&mut self);
    /// `Host.comPort.MAV.fencepoints`.
    fn fence_points(&mut self) -> Vec<FencePoint>;
    /// `Host.config[key]`.
    fn config_get(&mut self, key: &str) -> Option<String>;
    /// `Host.config[key] = value`.
    fn config_set(&mut self, key: &str, value: &str);
    /// `Host.MainForm.FlightData.saveTabControlActions()`, then `Settings.Instance.Save()`.
    fn save_tab_control_actions(&mut self);
    /// `FlightData.TabListOriginal.Add(tab)` and `tabControlactions.TabPages.Insert(index,
    /// tab)`: a flight screen page the plugin's form fills.
    fn flight_data_tab_add(&mut self, name: &str, text: &str, index: u32);
    /// The demo pointer to a named control, and its click (the owner's Welcome-Demo-Sitl).
    fn demo_click(&mut self, control: &str, millis: u32) -> bool;
    /// The demo pointer to a place on the map, and its click.
    fn demo_click_map(&mut self, lat: f64, lng: f64, millis: u32) -> bool;
    /// The same with the right button: the map's menu at that place.
    fn demo_right_click_map(&mut self, lat: f64, lng: f64, millis: u32) -> bool;
    /// The demo over: its pointer goes once its last gesture is done.
    fn demo_end(&mut self);
    /// Text typed into what has the keyboard, then Enter.
    fn demo_type(&mut self, text: &str);
    /// Whether a demo gesture is under way.
    fn demo_busy(&mut self) -> bool;
    /// Whether a named control is on screen.
    fn demo_visible(&mut self, control: &str) -> bool;
    /// `Host.FPGMapControl.SelectedArea`.
    fn fp_selected_area(&mut self) -> Option<Area>;
    /// `Host.FPGMapControl.ViewArea`.
    fn fp_view_area(&mut self) -> Option<Area>;
    /// `srtm.getAltitude`.
    fn terrain_altitude(&mut self, lat: f64, lng: f64) -> Option<f64>;
    /// `OpenFileDialog` and the read.
    fn open_file(&mut self, title: &str, filter: &str) -> Option<OpenedFile>;
    /// `SaveFileDialog` and the write.
    fn save_file(&mut self, title: &str, filter: &str, name: &str, data: Vec<u8>)
    -> Option<String>;
    /// A file under `Settings.GetUserDataDirectory()`.
    fn write_user_data(&mut self, path: &str, data: Vec<u8>) -> Result<String, String>;
    /// The plugin's form, drawn by the application.
    fn form_show(&mut self, title: &str, controls: Vec<Control>);
    /// The plugin's form closed.
    fn form_close(&mut self);
}

/// The world's `host` interface, answered by the plugin's [`Surface`].
impl wit::missionplanner::plugin::host::Host for plugin::State {
    fn cs(&mut self, name: String) -> Option<CsValue> {
        self.surface.cs(&name)
    }
    fn get_param(&mut self, name: String) -> Option<f64> {
        self.surface.get_param(&name)
    }
    fn param_options(&mut self, name: String) -> Vec<(i32, String)> {
        self.surface.param_options(&name)
    }
    fn set_param(&mut self, name: String, value: f64) -> bool {
        self.surface.set_param(&name, value)
    }
    fn set_mode(&mut self, mode: String) -> bool {
        self.surface.set_mode(&mode)
    }
    fn send_packet(&mut self, message_id: u32, payload: Vec<u8>) -> bool {
        self.surface.send_packet(message_id, payload)
    }
    fn menu_add(&mut self, menu: MapMenu, parent: Option<u32>, text: String) -> u32 {
        self.surface.menu_add(menu, parent, &text)
    }
    fn message_box(
        &mut self,
        text: String,
        caption: String,
        buttons: MessageButtons,
    ) -> DialogResult {
        self.surface.message_box(&text, &caption, buttons)
    }
    fn input_box(&mut self, title: String, prompt: String, value: String) -> Option<String> {
        self.surface.input_box(&title, &prompt, &value)
    }
    fn status(&mut self, text: String) {
        self.surface.status(&text);
    }
    fn log(&mut self, text: String) {
        self.surface.log(&text);
    }
    fn add_wp(&mut self, wp: Waypoint) -> i32 {
        self.surface.add_wp(wp)
    }
    fn insert_wp(&mut self, index: i32, wp: Waypoint) {
        self.surface.insert_wp(index, wp);
    }
    fn get_wps(&mut self) {
        self.surface.get_wps();
    }
    fn fence_points(&mut self) -> Vec<FencePoint> {
        self.surface.fence_points()
    }
    fn config_get(&mut self, key: String) -> Option<String> {
        self.surface.config_get(&key)
    }
    fn config_set(&mut self, key: String, value: String) {
        self.surface.config_set(&key, &value);
    }
    fn save_tab_control_actions(&mut self) {
        self.surface.save_tab_control_actions();
    }
    fn flight_data_tab_add(&mut self, name: String, text: String, index: u32) {
        self.surface.flight_data_tab_add(&name, &text, index);
    }
    fn demo_click(&mut self, control: String, millis: u32) -> bool {
        self.surface.demo_click(&control, millis)
    }
    fn demo_click_map(&mut self, lat: f64, lng: f64, millis: u32) -> bool {
        self.surface.demo_click_map(lat, lng, millis)
    }
    fn demo_right_click_map(&mut self, lat: f64, lng: f64, millis: u32) -> bool {
        self.surface.demo_right_click_map(lat, lng, millis)
    }
    fn demo_end(&mut self) {
        self.surface.demo_end();
    }
    fn demo_type(&mut self, text: String) {
        self.surface.demo_type(&text);
    }
    fn demo_busy(&mut self) -> bool {
        self.surface.demo_busy()
    }
    fn demo_visible(&mut self, control: String) -> bool {
        self.surface.demo_visible(&control)
    }
    fn fp_selected_area(&mut self) -> Option<Area> {
        self.surface.fp_selected_area()
    }
    fn fp_view_area(&mut self) -> Option<Area> {
        self.surface.fp_view_area()
    }
    fn terrain_altitude(&mut self, lat: f64, lng: f64) -> Option<f64> {
        self.surface.terrain_altitude(lat, lng)
    }
    fn open_file(&mut self, title: String, filter: String) -> Option<OpenedFile> {
        self.surface.open_file(&title, &filter)
    }
    fn save_file(
        &mut self,
        title: String,
        filter: String,
        name: String,
        data: Vec<u8>,
    ) -> Option<String> {
        self.surface.save_file(&title, &filter, &name, data)
    }
    fn write_user_data(&mut self, path: String, data: Vec<u8>) -> Result<String, String> {
        self.surface.write_user_data(&path, data)
    }
    fn form_show(&mut self, title: String, controls: Vec<Control>) {
        self.surface.form_show(&title, controls);
    }
    fn form_close(&mut self) {
        self.surface.form_close();
    }
}
