# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.es-ES.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 26 of 135 keys, and 8 orphan(s) the base file no longer has.

flightdata-pointCameraHereToolStripMenuItem-Text = Punto de Cámara Aquí
flightdata-BUT_quickmanual-Text = &Manual
flightdata-BUT_playlog-Text = Play/Pause
flightdata-goHereToolStripMenuItem-Text = Volar a Aquí
flightdata-BUT_RAWSensor-Text = Ver Sensor Raw
# orphan: no entry `TXT_alt.Text` in GCSViews/FlightData.resx
flightdata-TXT_alt-Text = 0
# orphan: no entry `lbl_windvel.Text` in GCSViews/FlightData.resx
flightdata-lbl_windvel-Text = Vel: 0
# orphan: no entry `TXT_long.Text` in GCSViews/FlightData.resx
flightdata-TXT_long-Text = 0
flightdata-BUT_log2kml-Text = Log > KML
flightdata-label1-Text = Zoom
flightdata-BUT_clear_track-Text = Limpiar Ruta
# orphan: no entry `dataGridViewImageColumn1.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn1-HeaderText = Up
# orphan: no entry `BUT_script.Text` in GCSViews/FlightData.resx
flightdata-BUT_script-Text = Script
flightdata-tabGauges-Text = Indicadores
flightdata-CHK_autopan-Text = Auto Pan
flightdata-BUT_joystick-Text = Joystick
flightdata-CB_tuning-Text = Tuning
# orphan: no entry `dataGridViewImageColumn2.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn2-HeaderText = Abajo
flightdata-BUTactiondo-Text = Hacer Acción
flightdata-BUTrestartmission-Text = Reiniciar Misión
# orphan: no entry `TXT_lat.Text` in GCSViews/FlightData.resx
flightdata-TXT_lat-Text = 0
flightdata-tabActions-Text = Acciones
flightdata-BUT_Homealt-Text = Establecer Altutid Casa
# orphan: no entry `lbl_winddir.Text` in GCSViews/FlightData.resx
flightdata-lbl_winddir-Text = Dir: 0
flightdata-BUT_loadtelem-Text = Cargar Log
flightdata-recordHudToAVIToolStripMenuItem-Text = Grabar HUD en AVI
flightdata-tabStatus-Text = Estado
flightdata-BUT_quickauto-Text = &Auto
flightdata-BUT_setwp-Text = Establecer WP
flightdata-tabTLogs-Text = Logs Telemetría
flightdata-lbl_logpercent-Text = 0.00 %
flightdata-BUT_setmode-Text = Configurar el modo
flightdata-stopRecordToolStripMenuItem-Text = Parar Grabación
flightdata-BUT_quickrtl-Text = &RTL
