# Generated by `cargo xtask codegen-resx` from GCSViews/FlightData.ru-RU.resx; do not edit here - edit the .resx, or the translation in Crowdin, and regenerate.
# 25 of 135 keys, and 7 orphan(s) the base file no longer has.

flightdata-goHereToolStripMenuItem-Text = Лететь сюда
flightdata-recordHudToAVIToolStripMenuItem-Text = Записывать HUD
flightdata-stopRecordToolStripMenuItem-Text = Остановить запись
flightdata-BUT_joystick-Text = Джойстик
flightdata-BUT_quickmanual-Text = РУЧНОЙ
flightdata-BUT_quickrtl-Text = БАЗА
flightdata-BUT_quickauto-Text = АВТО
flightdata-BUT_setwp-Text = Уст. WP
flightdata-BUT_setmode-Text = Уст. Режим
flightdata-BUT_clear_track-Text = Стереть трек
flightdata-BUT_Homealt-Text = Уст. высоту
flightdata-BUT_RAWSensor-Text = Просмотр сенсоров
flightdata-BUTrestartmission-Text = Перезап. Миссии
flightdata-BUTactiondo-Text = Выполнить
flightdata-tabActions-Text = Действия
flightdata-tabGauges-Text = Индикаторы
flightdata-tabStatus-Text = Статус
flightdata-lbl_logpercent-Text = 0.00 %
flightdata-BUT_log2kml-Text = Лог > KML
flightdata-BUT_playlog-Text = Старт/Стоп
flightdata-BUT_loadtelem-Text = Загрузить
flightdata-tabTLogs-Text = Логи телеметрии
# orphan: no entry `TXT_lat.Text` in GCSViews/FlightData.resx
flightdata-TXT_lat-Text = 0
flightdata-label1-Text = Увел.
# orphan: no entry `TXT_long.Text` in GCSViews/FlightData.resx
flightdata-TXT_long-Text = 0
# orphan: no entry `TXT_alt.Text` in GCSViews/FlightData.resx
flightdata-TXT_alt-Text = 0
flightdata-CHK_autopan-Text = Центровка
flightdata-CB_tuning-Text = Тюнинг
# orphan: no entry `lbl_windvel.Text` in GCSViews/FlightData.resx
flightdata-lbl_windvel-Text = Скор: 0
# orphan: no entry `lbl_winddir.Text` in GCSViews/FlightData.resx
flightdata-lbl_winddir-Text = Напр: 0
# orphan: no entry `dataGridViewImageColumn1.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn1-HeaderText = Вверх
# orphan: no entry `dataGridViewImageColumn2.HeaderText` in GCSViews/FlightData.resx
flightdata-dataGridViewImageColumn2-HeaderText = Вниз
